### PR TITLE
Update page in Connect AWS Gateway “tips-and-troubleshooting”

### PR DESCRIPTION
**Pull request by jcollins-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by jcollins-axway** [comment]
@kflan-io @dfeldick @sbolosan @vivekschauhan - please review for content

**Comment by jcollins-axway** [comment]
JIRA Tickets - APIGOV-15699 APIGOV-16040 APIGOV-15737

**Review by kflan-io — APPROVED** [review]

**Review by sbolosan — APPROVED** [review]

**Review by dfeldick — APPROVED** [review]

**Comment by jcollins-axway** [comment]
@cbordier - this is the last of the PRs I had that needs approval.

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop, please proceed.

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
