### PR TITLE
APIGOV-16392 - Update page in Connect API Manager “agent-variables”

### PR DESCRIPTION
**Pull request by vivekschauhan**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by jcollins-axway — APPROVED** [review]

**Review by lbadenhop — APPROVED** [review]

**Comment by lbadenhop** [comment]
@vivekschauhan Did you do a search on the docs for references to LOGSTASH, GETHEADERS, STATUS_PORT? I'm sure I've seen them referenced in other places.

**Comment by lbadenhop** [comment]
@vivekschauhan Can you please verify this JIRA number? I cannot acccess the JIRA.

**Comment by vivekschauhan** [comment]
@lbadenhop, sorry mentioned the wrong ticket number. Fixed

**Comment by vivekschauhan** [comment]
> @vivekschauhan Did you do a search on the docs for references to LOGSTASH, GETHEADERS, STATUS_PORT? I'm sure I've seen them referenced in other places.

@lbadenhop, I did find the reference for LOGSTASH_URL in /connect-api-manager/Agent-security-api-manager.md and /connect-aws-gateway/agent-security-aws.md, but could not see where these files are referenced

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop , please proceed.

**Pull request merged**
