### PR TITLE
APIGOV-18489 Add Upgrade an agent

### PR DESCRIPTION
**Pull request by lbadenhop**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Add topic to project under Connected agent - Common reference
https://deploy-preview-1819--axway-open-docs.netlify.app/docs/central/connected_agent_common_reference/upgrade_agent/

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by lbadenhop** [comment]
@cbordier Topic created and ready for you to add content

**Comment by cbordier** [comment]
@lbadenhop, it is ready for review.

**Comment by lbadenhop** [comment]
@cbordier I made a lot of edits. Please review before I merge.

**Comment by cbordier** [comment]
@lbadenhop, I asked Leor to review it before merging. He has some inputs I will incorporate. Then I will let you know when I am done with the review

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop, can you have a final check and proceed?

**Pull request merged**
