### PR TITLE
Update page in Connect API Manager “deploy-your-agents”

### PR DESCRIPTION
**Pull request by sbolosan**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@sbolosan Can you please review one more time?

**Comment by sbolosan** [comment]
Looks good...  thank you

**Comment by lbadenhop** [comment]
@alexearnshaw @andreamussap Please upload to docs.axway.com

**Comment by cbordier** [comment]
@lbadenhop can you remove the alert at the beginning of the page.

**Comment by alexearnshaw** [comment]
@lbadenhop This PR and all PRs merged before this are now pushed to prod

**Pull request merged**
