### PR TITLE
Fix broken link in Connect API Manager “network-traffic-apimanager”

### PR DESCRIPTION
**Pull request by lbadenhop**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@cbordier Ready for your review. It's a broken link Dale found and a missing ) character.

**Review by cbordier — COMMENTED** [review]
I approve the changes

**Comment by lbadenhop** [comment]
@cbordier I cannot merge until you accept the change under Files changed tab.

**Review by cbordier — APPROVED** [review]
I approve the changes

**Pull request merged**
