### PR TITLE
Update page in Connect AWS Gateway “deploy-your-agents-1”

### PR DESCRIPTION
**Pull request by jcollins-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by jcollins-axway** [comment]
@kflan-io, @sbolosan, @dfeldick 

Please review the Subscription content, here is the preview link.
https://deploy-preview-981--axway-open-docs.netlify.app/docs/central/connect-aws-gateway/deploy-your-agents-1/

**Comment by jcollins-axway** [comment]
APIGOV-15466

Add details on using subscription notification configuration

**Comment by dfeldick** [comment]
Looks nice.

**Comment by jcollins-axway** [comment]
@lbadenhop - ready for review

**Comment by lbadenhop** [comment]
@cbordier Do you want to review before I merge to master?

**Pull request merged**
