### PR TITLE
Add estimated reading time ERT to the pages

### LINKED ISSUE #204: [DOC] remove estimated reading time from AMPLIFY Central docs
## Issue description

Estimated reading time (ERT) is the first information that the user sees in the page after the heading, and sometines, after a short description. When the user lands in a page with ERT they can decide right way if they want to engage with that content or not, based on the ERT. A long ERT might make some users to give up reading the topic even before they start it. 

Nevertheless, ERT can be a helpful feature for specific types of contents: 

> Customers are constantly looking for ways to improve their content marketing so they can engage with their target audience more effectively. That's why we added a brand new feature to our platform called 'Estimated Reading Time.' We now automatically calculate ERT for the following content types:  Blog Posts, SEO Content, News Commentaries, Informative Articles and Thought Leadership ([source](https://www.tempestamedia.com/press-releases/new-feature-estimated-reading-time-improves-content-marketing-results-and-engagement/))

However, more technical conceptual information, tasks, and procedures requires attention. These are types of content that you read thoroughly in order to learn something, so you can't simply scan it. The time of learning is different for different people. Also, in a long page, with more than one procedure, maybe with some explanation and some procedures, it doesn't mean that the user who just landed there wants to execute all procedures documented in the page. They might want/need just part of what's there, in this case ERT doesn't make sense because different users will use that content in different ways, consequently, in different time frames.

Some examples of documentation Portals that **don't** use ERT:

- https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

- https://docs.aws.amazon.com/storagegateway/latest/userguide/create-gateway-file.html

- https://tyk.io/docs/get-started/with-tyk-cloud/create-an-account/

- https://docs.apigee.com/api-platform/get-started/create-proxy

## Problem location

https://axway-open-docs.netlify.com/docs/central/

## Suggestions for a fix

Remove ERT from the pages.

### PR DESCRIPTION
**Pull request by andreamussap**
Closes #204 

## Describe the changes

- Add new readingtime config param in userguide `config.tom`
- Copy themes/docsy/layouts/docs/list.html to `'docascode'/layouts/docs/list.html`
- Copy themes/docsy/layouts/_default/content.html to `'docascode'/layouts/` and add conditional block for reading time
- Create new file `layouts/partials/reading-time.html`
- Update `static/admin/config.js` to remove `ReadingTime` and `WordCount` fields that I've unnecessarily added in a previous commit.

**Remove estimated reading time (ERT) from landing pages.**

* Remove _manual_ estimated reading time (ERT) from Central pages.
* Remove ERT from landing pages. Some of them showed "0 mins", and the rest (or at least the vast majority, "1 mins".
* Remove ERT from _internal_ landing pages. They were either showing 0 or 1 min.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@andreamussap Well done for taking a stab at this! You're on the right track but when you want to add something to all pages (or at least multiple pages) it's best to modify the site templates rather than modifying individual pages. I think the Hugo variables are only available in template files and not directly in Markdown files.
Coincidentally, I had submitted a PR to add reading time a while ago to the Docsy theme - https://github.com/google/docsy/pull/209 - This should give you a good idea of how to do this type of thing :)

I didn't add the functionality to our project as I was hoping we would upgrade to the latest version of Docsy at some stage and then we'd get that functionality (and other cool stuff they've added) out of the box.

**Comment by andreamussap** [comment]
Deploy preview

https://deploy-preview-894--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_admin/

**Comment by andreamussap** [comment]
> @andreamussap Well done for taking a stab at this! You're on the right track....

@alexearnshaw  thanks. I read the issue you linked, and all its references, and I've made some changes but still not working. I'll talk to you tomorrow

**Comment by andreamussap** [comment]
@alexearnshaw It worked!!! :)

PR894_readingtime_netliffy

**Comment by alexearnshaw** [comment]
@andreamussap Great, well done!!! 
I think we should go ahead and add it. I noticed on a few of the section landing pages that have no content apart from the auto TOC of sections it shows "0 mins" so think we should turn it off in the frontmatter for those pages. Everywhere else it looks fine :)

**Comment by alexearnshaw** [comment]
@andreamussap Re "Create an issue or PR to remove manual reading time from APIC pages." I think we already have this in #204 ? Can you do it as part of this PR as this is already linked to close that issue?

**Comment by andreamussap** [comment]
@alexearnshaw  re so think we should turn it off in the frontmatter for those pages --> Yes! I was thinking that makes sense to turn it off in some pages. Just wanted to discuss with you first.

#204 re Can you do it as part of this PR --> sure!!

**Pull request merged**
