### PR TITLE
Initial commit of Streams v2 documentation

### PR DESCRIPTION
**Pull request by allandenis38**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Initial commit of Streams v2 (Beta) documentation

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [x] Does not have conflicts with the base branch
* [x] Is clear and complete
* [x] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [x] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [x] Passes the Markdown linter rules (automated via CI check)
* [x] Does not contain broken links
* [x] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [x] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [x] You have applied a production label if this needs a manual push to Zoomin
* [x] You have added it to the correct GitHub project
* [x] You have added it to the correct Sprint milestone
* [x] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [x] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@allandenis38 Thanks, this looks good! You have 2 minor linting errors in your files, to do with extra trailing spaces at the end of lines. 
image

You can remove the extra spaces on the files/lines indicated above and commit and the check should then pass, or I can remove them when I do the review and merge. Let me know, thanks Alex

**Comment by allandenis38** [comment]
> @allandenis38 Thanks, this looks good! You have 2 minor linting errors in your files, to do with extra trailing spaces at the end of lines.
> image
> 
> You can remove the extra spaces on the files/lines indicated above and commit and the check should then pass, or I can remove them when I do the review and merge. Let me know, thanks Alex

Hi @alexearnshaw, yes please remove it when you do your review, thanks Allan

**Comment by alexearnshaw** [comment]
@allandenis38 I've fixed the lint errors and also made a couple of other minor changes, please review the other changes on my commit https://github.com/Axway/axway-open-docs/pull/617/commits/35db60479cb5094a8ec1d0d5ad40bee218c98912 and let me know if this is ok?

If you want users to be able to use the CMS to edit the Streams topics you'll also need to add new CMS collections for each subfolder as detailed in http://localhost:1313/docs/contribution_guidelines/maintain_customize/#add-new-documentation-to-netlify-cms

Note that I haven't reviewed the content for Axway style as I don't have the capacity to check this as part of this review. If you don't have a tech writer assigned to Streams then I guess you'll have to do your best to make sure the doc follows the style guide yourself (see https://techweb.axway.com/confluence/display/RIE/Style+guide).

**Comment by allandenis38** [comment]
> If you want users to be able to use the CMS to edit the Streams topics you'll also need to add new CMS collections for each subfolder as detailed in http://localhost:1313/docs/contribution_guidelines/maintain_customize/#add-new-documentation-to-netlify-cms
I've added streams folder to Netlify CMS collections config file in my latest commit.

**Comment by alexearnshaw** [comment]
> I've added streams folder to Netlify CMS collections config file in my latest commit.

Thanks! I've also noticed that you have a couple of subfolders underneath the main `streams` folder and they will also need to be added as collections or users won't be able to edit topics in those subfolders using CMS. It's a bit of a pain but the CMS doesn't currently automatically read subfolders so each one needs to be added as another collection. Take a look at the collections for AMPLIFY Shared Services for an example.

Alternatively, you could merge the topics in the `publishers`/`subscribers` subfolders into one longer topic each for subscribers and publishers? In this case, you wouldn't need to define any additional collections in the config and it also might give a slightly better UX as users would be able to see all the content pertaining to subscribers or publishers in a single page without having to use extra clicks to navigate through it, and they'd be able to search it more easily with Ctrl-F.

I'd recommend the latter, but it's your call. Let me know if you'd prefer to discuss this on a call.

**Comment by allandenis38** [comment]
Hi @alexearnshaw, I've added streams subfolders to CMS config files. This seemed to be the simplest solution thanks to the example with AMPLIFY Shared Services. Also, I am not able to clearly visualize what would be the ux with a merged topic. Maybe you can show it to me so we add it later.

**Comment by alexearnshaw** [comment]
@allandenis38 Thanks a lot. I've merged this now. I've also created an issue for us to perform a deeper review #642 as soon as we can.
One last question - do you want this to be visible to public users on docs.axway.com or should it be restricted to internal only for now?

**Comment by allandenis38** [comment]
@alexearnshaw Thanks for the merge. Let's keep it restricted for now as Streams v2 is at a technical preview stage and only available through Axway Early Adopter program for now.

**Pull request merged**
