### PR TITLE
Update page in Connect AWS Gateway “prepare-aws-api-gateway”

### PR DESCRIPTION
**Pull request by cbordier**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by cbordier** [comment]
@jcollins-axway , @lbadenhop : can you review the changes?

**Comment by cbordier** [comment]
@lbadenhop, I reorganize using the ## and * markdown delimiters and I am satisfied with the result.
Can you review it?

**Comment by lbadenhop** [comment]
Hi @alexearnshaw and @andreamussap Please upload to docs.axway.com.

**Comment by alexearnshaw** [comment]
> Hi @alexearnshaw and @andreamussap Please upload to docs.axway.com.

@lbadenhop  This (and all PRs merged prior to this) are now on prod

**Pull request merged**
