### PR TITLE
RDAPI-17279: new blog about doc-as-code beta availability

### PR DESCRIPTION
**Pull request by andreamussap**

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@andreamussap I had a quick look at this and although it's fine, maybe we need to think more about this Netlify blog, as it will be publicly accessible to external customers, and we don't want to make too much information public, and some of the links (e.g. confluence) won't be accessible to external users. We probably need a slightly different version of the post for this blog? But maybe that's duplication of effort?

**Comment by andreamussap** [comment]
@alexearnshaw RE some of the links (e.g. confluence) won't be accessible to external users - I know. I added 'requires Axway login' to one of them but I probably forgot the others. Anyways I don't think this is a good approach, keep internal links and say that external ppl can't access. Howerver, creating two versions of the 'same' blog is dupplication of effort, which I don't think is worth, specially because it will take a while until the Netlify site goes public. In fact it won't be one text anymore, we'll have to write two texts. I wonder the value of this...

When Netlify is advertised to externals, maybe the solution will be to create a text/blog unique for both internal/external audience, that is, without internal links. The ideal world would be to publicize only on Net/blog but then, I'm pretty sure that many Axway ppl will miss it.
For this one, what do you want, should I tidy it up for external audience?

**Comment by alexearnshaw** [comment]
@andreamussap yes need to think out this strategy a little more ;) For now let's just do a very short post for this blog, just highlighting that the solution is now available and which documentation is open for editing and pointing to the contrib guidelines?

**Comment by andreamussap** [comment]
@alexearnshaw let me know if it's ok now.

Do you think should remove this part 'Open source docs is a growing trend. Other big companies such as Docker, Amazon, and Microsoft have opened their documentation for collaboration using a GitHub forking and pull request workflow.' ?

**Pull request merged**
