### PR TITLE
Synchronize AWS and Azure ref arch common content

### PR DESCRIPTION
**Pull request by ingo**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Align the common elements of the reference architectures across the AWS and Azure documents

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [X] You have verified that all status checks have passed

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Passes all status checks
* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by andreamussap** [comment]
**AMPLIFY API Management container reference architecture on AWS** review: 

https://deploy-preview-1282--axway-open-docs.netlify.app/docs/apim-reference-architectures/container-aws/

- Remove empty space at the end of the sentences, wrapping text properly in the markdown file so it does not create unnecessary `diffs` when the page is updated. This also makes it easier to contribute, review, and maintain.
- Change of word choice for [Axway Style](https://techweb.axway.com/confluence/display/RIE/Quick+Reference+Do%27s+and+Don%27t%27s) compliance.
- Changes to improve readability.

**Comment by andreamussap** [comment]
AMPLIFY API Management container reference architecture on **Azure** review:

https://deploy-preview-1282--axway-open-docs.netlify.app/docs/apim-reference-architectures/container-azure/

- Remove empty space at the end of the sentences, wrapping text properly in the markdown file so it does not create unnecessary diffs when the page is updated. This also makes it easier to contribute, review, and maintain.
- Change of word choice for Axway Style compliance.
- Changes to improve readability.

**Review by andreamussap — APPROVED** [review]

**Comment by ingo** [comment]
Hi Andrea. Thank you for merging this. Unfortunately, the subsequent changes undid most of my work. The primary goal was to make sure that the content was identical between the AWS and Azure version (and I mean identical in a diff context) so that it was easy to see if there was an update in one that it should be applied to another and to allow for eventual consolidation of the content into blocks that can be inserted into both documents.

That's no longer the case. 

For instance in AWS: https://github.com/Axway/axway-open-docs/blob/master/content/en/docs/apim-reference-architectures/container-aws/_index.md

Pod resource limits
"Kubernetes uses these limits to ensure that resources for _the_ pod are available on a target node."

vs Azure:https://github.com/Axway/axway-open-docs/blob/master/content/en/docs/apim-reference-architectures/container-azure/_index.md

Kubernetes uses these limits to ensure that resources for _a_ pod are available on a target node.

You can see where I made the change here from "the" to "a" in AWS as Azure appeared to be the "newer" version: https://github.com/Axway/axway-open-docs/pull/1282/commits/a135a5076121060aeb9ff986991aedfe531598e0#diff-62e2ceba50a7104d04d0921d4f4c2e4bL449

And that was then undone here: https://github.com/Axway/axway-open-docs/pull/1282/commits/1a31f4972c1ebac149daffb2886749f802e20264#diff-62e2ceba50a7104d04d0921d4f4c2e4bL468

I don't mind if you update stylistic notes from "a" to "the" but I would say that both documents should be updated the same, and the line breaks should be identical.

Anyway, if you'd like to do what I did, I used a diff tool to compare the two documents and align the contents wherever possible. I think it will make future upkeep easier for the team.

**Comment by andreamussap** [comment]
Hi Ingo, sorry for that. These files are huge, so what I did was to make as much improvements as possible, and I knew that there would be more updates/reviews later so it would be possible to keep improving them with time. But I get and agree with your point, so please tell me about this diff tool.

**Pull request merged**
