### PR TITLE
RDAPI-26539 ChangeLog Updates for 2021 releases

### PR DESCRIPTION
**Pull request by pfoleyAx**
Thank you for your contribution to the Axway-Open-Docs repo.

ChangeLog Updates

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

https://deploy-preview-2223--axway-open-docs.netlify.app/docs/apim_reference/allreleaseschangelog/

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by pfoleyAx** [comment]
Still in Draft Stage and Under review.

**Review by jmbermingham — APPROVED** [review]
Looks good, I like the improved formatting of the table for the updates.

**Comment by jowens-axway** [comment]
looks like this page might have fallen through the doc cracks, does not seem to be on the release tasks to ensure it gets updated

**Review by jowens-axway — APPROVED** [review]

**Comment by jowens-axway** [comment]
it also looks like this page has never been updated for portal, again release checklist issue I'm assuming. this page will likely need reformatting to ensure its clear what product we are talking about if we are going to add portal info into here @jmbermingham thoughts here?

**Comment by jmbermingham** [comment]
> it also looks like this page has never been updated for portal, again release checklist issue I'm assuming. this page will likely need reformatting to ensure its clear what product we are talking about if we are going to add portal info into here @jmbermingham thoughts here?

It came from a customer request to have a change log in place - the request was for Gateway/Manager, that said you are correct, we should have one for Portal too (or at least make it clear) - @jowens-axway lets look at doing a change log for Portal for the next release.

**Pull request merged**
