### PR TITLE
Update page in Connect API Manager “deploy-your-agents”

### PR DESCRIPTION
**Pull request by jcollins-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by jcollins-axway** [comment]
APIGOV-15214

**Comment by jcollins-axway** [comment]
@lbadenhop - ready for review

**Comment by lbadenhop** [comment]
@jcollins-axway Please review my changes.

**Comment by lbadenhop** [comment]
@alexearnshaw @andreamussap Please upload to docs.axway.com

**Pull request merged**
