### PR TITLE
Remove Cumulative script announcement for July release , since new one was released and this one was removed from webliv 

### PR DESCRIPTION
**Pull request by dginevaAxway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by dginevaAxway** [comment]
NO Jira for this one, was left after the release of November release notes

**Comment by andreamussap** [comment]
@dginevaAxway  but why deleting historical information? Looking at the section, it links to [Upgrade API Portal using the cumulative upgrade script](https://axway-open-docs.netlify.app/docs/apim_installation/apiportal_install/upgrade_automatic/#upgrade-api-portal-using-the-cumulative-upgrade-script).

What's the harm in leaving the section there? That was an important information by the time of the July release. Just because things have changed, you don't need to delete if from there as long as we are keeping the new release pages up to date ??

I'd suggest close this PR whithout merging it because there's no need to delete this historical information ??
cc @jowens-axway

**Comment by jowens-axway** [comment]
@andreamussap the script that that section in the release notes has been removed from webliv and replaced by a new script under the Nov 20 update so that is why Dimi is removing the section from the release notes - the script it refers to no longer exists under July 20 assets in webliv. Hope that makes a bit more sense now.

**Comment by andreamussap** [comment]
> the script it refers to no longer exists 

Ah! Now I get it. Thanks.

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
