### PR TITLE
Update page in external connections section “common_db_conf”

### PR DESCRIPTION
**Pull request by mvenzke-axway**
Automatically generated by Netlify CMS

https://deploy-preview-1493--axway-open-docs.netlify.app/docs/apim_policydev/apigw_external_connections/common_db_conf/#test-the-connection

### CODE REVIEW

**Comment by andreamussap** [comment]
@mvenzke-axway I'd suggest move the new sentence a bit . Would this work?

'When you have specified all the database connection details, you can click the **Test Connection** button to verify that the connection to the database is configured successfully. (Requires network connectivity between Policy Studio and the database server). This enables you to detect any configuration errors at design time instead at runtime.'

**Comment by mvenzke-axway** [comment]
That works fine.  I feel like the parentheses are unnecessary again, but that's ok.  Maybe change the last two sentences to:  "This requires network connectivity between Policy Studio and the database server and enables you to detect any configuration errors at design time instead at runtime."

**Comment by andreamussap** [comment]
@mvenzke-axway 'Requires network' is a prerequisite, 'enables to detect' is consequence of clicking the button - the two sentences aren't connected. What about the following?

After you have specified all the database connection details, ensure that (your network can connect / there is a connection stablished between) Policy Studio and the database server, and click the **Test Connection** button to verify that the connection to the database is configured successfully, and to detect any configuration errors at design time, instead at runtime.

**Comment by mvenzke-axway** [comment]
That's a bit awkward.  But your note about it being a prerequisite gives me a clue that the sentence needs to come earlier.  Maybe this?

'When you have specified all the database connection details and ensured that Policy Studio can make a network connection to the database server, you can click the Test Connection button to verify that the connection to the database is configured successfully.  This enables you to detect any configuration errors at design time instead at runtime.'

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
