### PR TITLE
Create page in AMPLIFY Central section “amplify-central-october-2020-release-notes”

### PR DESCRIPTION
**Pull request by lbadenhop**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@cbordier Please review and then delete your merge request.

**Review by cbordier — APPROVED** [review]
I approve the changes,
@lbadenhop can you review the wording/formatting

**Comment by lbadenhop** [comment]
@robertengaxway, @georgiana-caras, @markbice, @cbordier  Please do a final review of the Release notes no later than noon tomorrow. All headings should be followed by an introductory sentence. See lines 13, 71, 94, 176 and 220.

**Review by cbordier — COMMENTED** [review]
Done with the introduction sentence,
@lbadenhop, you can review

**Pull request closed without merging**
