### PR TITLE
Create Pages and collection for AMPLIFY Central Release notes Oct 2020

### PR DESCRIPTION
**Pull request by andreamussap**
In this PR:

- Created folder amplify_relnotes
- Created _index.md page (landing page)
- Update config.js file to add collection for AMPLIFY Release notes (This makes the pages under this menu available for editing on CMS)
- Created a test page just to see how it looks (to be removed) RN_test.md

@lbadenhop @cbordier  If I can give you a suggestion, I see that you've named your page `amplify-central-october-2020-release-notes.md` ([PR#1359](https://github.com/Axway/axway-open-docs/pull/1359)). When you start creating more pages, it would be easier and quicker to search, find, order, and maintain with shorter names ordered by date, e.g., `20201030_ampc_relnotes.md`. You don't need more than that IMHO.  

Also, the frontmatter of your page is missing the `linkTitle` parameter. You must add it or it will cause issues to display this page on CMS, and maybe even on the website. On the other hand, you can remove the `Description` parameter. It's unnecessary on release notes pages, all info that you need is already on the body of the page

https://deploy-preview-1360--axway-open-docs.netlify.app/docs/central/amplify_relnotes/

### CODE REVIEW

**Comment by andreamussap** [comment]
@cbordier can I merge this?  @lbadenhop 

https://deploy-preview-1360--axway-open-docs.netlify.app/docs/central/amplify_relnotes/

PR1360_website

**Comment by cbordier** [comment]
@andreamussap, @lbadenhop 
I think the wording is not correct: it should be either  "AMPLIFY Central Release Notes" or "Release Notes" only. My preference is "Release Notes" as we already are in Central category.  AMPLIFY is the entire Axway platform where Central is only a subset of it.
Could this folder be on the just under AMPLIFY Central instead of at the bottom of the list?

**Review by cbordier — APPROVED** [review]

**Review by cbordier — CHANGES_REQUESTED** [review]
Change the name to "Release Notes"
Put this section right under AMPLIFY Central

**Comment by lbadenhop** [comment]
@andreamussap Can you please merge as soon as you make Cyrille's changes (change name and location of release notes folder)? Then I'll be able to upload to production today. Also, maybe we can step through the process next week so I'll know how to do it next time?

**Comment by andreamussap** [comment]
@cbordier  @lbadenhop Done!  https://axway-open-docs.netlify.app/docs/central/amplify_relnotes/  You can move the RN page there.

**Pull request merged**
