### PR TITLE
[RDAPI-17488] setup-cassandra script doc improvements

### PR DESCRIPTION
**Pull request by dsantosaxway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by dsantosaxway** [comment]
## Deploy Preview Links
https://deploy-preview-1834--axway-open-docs.netlify.app/docs/cass_admin/cassandra_setup_script

**Comment by dsantosaxway** [comment]
@kmercierwhite Please review!

**Comment by andreamussap** [comment]
Ongoing discussion under RDAPI-17488.

**Comment by andreamussap** [comment]
@dsantosaxway All fine by me, but waiting for @kmercierwhite  to approve the PR so I can merge it.

**Review by kmercierwhite — APPROVED** [review]
Yeah I think this addresses the key issues! Thanks Diogo!

**Pull request merged**
