### PR TITLE
RMF-442 Reference architectures Update EMT terminology to Container and other improvements

### PR DESCRIPTION
**Pull request by andreamussap**
http://pr-2751.axway-open-docs.opendocs-builder.pcloud.axway.int/docs/apim-reference-architectures/container-aws/

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">âœ…</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">ðŸ”¨</span> Latest commit | c4e8993c |
 |<span aria-hidden="true">ðŸ˜Ž</span> Deploy preview | http://PR-2751.axway-open-docs.opendocs-builder.pcloud.axway.int |

**Comment by sridhar2010** [comment]
https://github.com/Axway/axway-open-docs/blob/RMF-442_brokenlink/Images/apim-reference-architectures/container-aws/image1.png Image links are broken

**Review by ingo — COMMENTED** [review]
Minor issues except the discussion around building vs. using pre-built images. Asked Aidan/John..I think that piece needs to be rewritten.

**Comment by andreamussap** [comment]
I have resolved the editorial suggestions. The technical questions and suggestions must be addressed by way of the ARCH-164 epic.

**Pull request merged**
