### PR TITLE
New section Get started with AMPLIFY Central CLI

### PR DESCRIPTION
**Pull request by robertengaxway**
Thank you for your contribution to the Axway-Open-Docs repo.

These changes were meant to consolidate the AMPLIFY Central CLI docs into one subsection called "Getting Started with the AMPLIFY Central CLI".
Also added more use case examples for creating resources in an environment and the Unified Catalog. 

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

R&D reviewers, Please check the CLI command and configuration file content.
PMs/POs, Please check the content and usability of the docs.
Tech Doc reviewers, Please also check documentation links and formatting.

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers
Lorri Petty
Mark Bice 
Georgiana Caras
Cyrille Bordier (cbordier)
Alexey Grakhov (agrakhov)
Ravi Savajiyani (rsavjiyani)
Shiva Janagam (sjanagram)
Steve Marshal (stevesonoa)

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [X] Does not have conflicts with the base branch
* [X] Is clear and complete
* [X] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [X] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [X] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [X] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [X] Does not contain typos, grammatical errors, etc.
* [X] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [X] Does not contain broken links
* [X] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by andreamussap** [comment]
Direct link to eploy preview - https://deploy-preview-859--axway-open-docs.netlify.app/docs/central/cli_central/ 

@robertengaxway  **On this first review:**

- I've fixed lots of markdownlinter errors.
- I've updated some headings: all these pages are under the  Get started with AMPLIFY Central CLI menu, and all of them mention 'use AMPLIFY Central CLI' in the Description, so I don't think it's necessary to add ' use AMPLIFY Central CLI' in the titles. So I've changed:

Use the AMPLIFY Central CLI to Manage an Axway SaaS Gateway API proxy --> Manage an Axway SaaS Gateway API proxy
Use the AMPLIFY Central CLI to build an API Service --> Create an API Services to represent your environments

**To be continued**:

- I'll review and probably change the other headings.
- I'll move the JSON files to the [Reference](https://axway-open-docs-redirect-test.netlify.app/docs/apim_reference/) section because these pages are definetly cluttered with them embedded.
- I'll perform the 'content' review.

@robertengaxway  Can I ask you to not make further changes to these files? This PR is already huge, and it's hard to work and see the entire picture with something so big. So if you could let me finish this review and merge the changes, then I think it would be better for you/your team to make more improvements, as well as for me to perform a better review of the content.

**Comment by andreamussap** [comment]
@robertengaxway 
I've been working on this review since Wednesday, and I did a lot so far:

- Fixed lots of markdown errors.
- Made changes to improve readability and to comply with Axway style, standards.
- Moved all samples to folder /resources/central/ and added reference to the samples in the doc pages. (Sample codes in the middle of long pages clutters the page, but we can review and discuss this further)
- Reestructured some sections or paragraphs.
- Removed promisses ('This or that is comming soon'). This is a technical document, so no need for ads or marketing information. When a feature is available, just update the doc with it.
- Added AMPLIFY Central CLI to config.js to make it available from the CMS, and so on.

Since you need to show this on today's AMPLIFY Central Demo, I'm merging this PR, and you and the other reviewers and keep updating and improving the contents after that. This was an initial review, and I can see that there's a lot still to improve and clarify but we cannnot and should not try to do all at once. Let's improve it bit by bit.

/Andrea.

**Comment by andreamussap** [comment]
Get started with AMPLIFY Central CLI is available on Netlify portal now - https://axway-open-docs.netlify.app/docs/central/cli_central/cli_install/ 

All pages are also available for edition from the CMS - https://axway-open-docs.netlify.app/admin/#/collections/cli_central

**Comment by ingo** [comment]
This PR appears to rename cli_getstarted.d to cli_install.md and then breaks links in

https://docs.axway.com/bundle/axway-open-docs/page/docs/central/cli_central/cli_apiservices/index.html
https://docs.axway.com/bundle/axway-open-docs/page/docs/central/cli_central/cli_environments/index.html

**Pull request merged**
