### PR TITLE
Update page in Connect AWS Gateway “deploy-your-agents-1”

### PR DESCRIPTION
**Pull request by sbolosan**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by sbolosan** [comment]
@cbordier I have no idea... i think i've seen that on basically all my changes, even if its just a 1 word change.

**Comment by cbordier** [comment]
@amussapvordel, @alexearnshaw  Can you have a look to the diff that Shane proposed. There are a lot whereas he really update line 133.
This has been done using netlify UI directly.

**Comment by andreamussap** [comment]
> @amussapvordel, @alexearnshaw Can you have a look to the diff that Shane proposed. There are a lot whereas he really update line 133.
> This has been done using netlify UI directly.

Hi @cbordier I had a look at the diff https://github.com/Axway/axway-open-docs/pull/1032/files It seems that the CMS has made some changes to the tables to "fix" some formatting. Unfortunatelly, this happens when we migrate files and don't tyde up the tables, or spaces in paragraphs etc, so the CMS "fixes" it itself. Probably, the next time you edit this file (/docs/central/connect-aws-gateway/deploy-your-agents-1.md) you won't see these lots of changes again.

To know what actually changed in the content, you can look for the part where the color is stronger:
PR1032

**Comment by lbadenhop** [comment]
@sbolosan can you please provide the Jira number?

**Comment by sbolosan** [comment]
@lbadenhop this is the subtask I created.  https://jira.axway.com/browse/APIGOV-15726  but could not create a doc task under a subtask so I just mentioned it in the ticket (comments)

**Pull request merged**
