### PR TITLE
Update page in Connect API Manager “gateway-administation”

### PR DESCRIPTION
**Pull request by kflan-io**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@sbolosan @kflan-io @jcollins-axway @dfeldick Please review

**Comment by jcollins-axway** [comment]
I do not see anything including the environment overrides for the Traceability agent.

**Comment by lbadenhop** [comment]
Hi @alexearnshaw and @andreamussap,
Please HELP! Do you know why the Netlify deploy preview check isn't completing?

**Comment by alexearnshaw** [comment]
> Hi @alexearnshaw and @andreamussap,
> Please HELP! Do you know why the Netlify deploy preview check isn't completing?

@lbadenhop I'm not sure, we have the same issue in some of ours. Yesterday the integration between Netlify and Github got removed by accident, but it has been restored now so everything should be back to normal. Do you want us to merge the affected PRs with our admin privileges?

**Comment by lbadenhop** [comment]
Hi @alexearnshaw,
Please merge this PR request and #988. This morning I committed a change with a "Test" comment. I don't see the comment in the Conversations tab, but I do see my latest change in the Files changed tab. The checks still are not completing.
Thanks

**Pull request merged**
