### PR TITLE
Create section “zero-downtime-api-updates”

### PR DESCRIPTION
**Pull request by mvenzke-axway**
Automatically generated by Netlify CMS

Deploy preview - https://deploy-preview-1418--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web/#perform-zero-downtime-updates-to-an-api

### CODE REVIEW

**Comment by mvenzke-axway** [comment]
New section for RDAPI-13673

**Comment by andreamussap** [comment]
@mvenzke-axway , a page which is 1 minute read... I'm not sure if we need a new content/page for this. We want to avoid customers leaving the content to other pages, and getting lost and giving up reading the doc. But, same as you, I don't know where this would fit better, if there's a related content where you could add this as a section. 

So I'm going to ask for @jpfaffenzeller @kmercierwhite @cwiechmann help - can you guys tell me and Matthew if there's an existent section in the documentation, with subject related, and where we could add the content of this short page as a subsection?

Deploy preview of the content - https://deploy-preview-1418--axway-open-docs.netlify.app/docs/apim_howto_guides/zero-downtime-api-updates/

**Comment by cwiechmann** [comment]
I'm really happy to see people contributing in that new How-To-Section and that was really the intent to share knowledge from the field. 

However, for that topic I would propose to place it here as it is strongly relates to register & manage APIs.
https://deploy-preview-1418--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/

And create back-links from these pages: 
https://deploy-preview-1418--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_register_web/ 
& 
https://deploy-preview-1418--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web/

**Comment by andreamussap** [comment]
Thank you, Chris but my point is that I don't think it's needed to create a new page just for this instruction :). I think that this new information could be a section at the end of [Virtualize REST APIs in API Manager](https://deploy-preview-1418--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web/).

@mvenzke-axway , one thing that worries me is the amount of screenshot - if there's a typo fixed in one of these screens, the screenshot should be replaced (see, https://jira.axway.com/browse/RDAPI-22393). However, nobody is going to track this down to update the docs. So, is it possible to add more text (explanatory information) to this section in order to cut off some of the screeshots?

**Comment by cwiechmann** [comment]
Yes, I agree @andreamussap! It makes sense to me what you proposed concerning the page. But I do prefer screenshots over more text to explain a certain topic. And even if the screenshot is not 100 percent up to date with the product, it helps anyway in my opinion.

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
