### PR TITLE
Update page in Connect API Manager “discovery-agent-variables” (APIGOV-15215)

### PR DESCRIPTION
**Pull request by dfeldick**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@dfeldick Pleasse review before I merge. Thanks

**Comment by dfeldick** [comment]
APIGOV-15215

**Comment by dfeldick** [comment]
@lbadenhop changes look ok

**Comment by lbadenhop** [comment]
@alexearnshaw @andreamussap Please upload to docs.axway.com.

**Pull request merged**
