### PR TITLE
Update fundamental_concepts.md

### PR DESCRIPTION
**Pull request by robertengaxway**
In preparation for OUM Uplift Go live.   Refer to ticket APIGOV-10119

### CODE REVIEW

**Comment by robertengaxway** [comment]
> @robertengaxway I've made some editorial updates so this is ready to merge now. But just wondering do you want to add a little more info about what capabilities each role has in APIC, or is that available in the UI (or customizable in the UI)?

Yes, I would like to add more info about the capabilities of each role.  I dont think it belongs in the Central Concepts section.  I was hoping to have inputs from additional contributors such as Melissa Colins/Georgiana Caras/Mark Bice.   But I could not find a way to add more reviewers on the Github.
The key question is creating a new section in Central for the capabilities or adding to the Plaform section which owns the roles?

**Comment by markbice** [comment]
I think this needs to be its own New topic under Concepts and not just under the API Proxy concept.
And we may need to list out (bullets) the 3 supported Roles to make them... and then their management context clearer... perhaps even listing the limited menu views that Consumer has.
And before we are done, we may need to explain that a user can have a different role on each of the teams they are a member of. This part is typically not obvious to new users.

**Comment by alexearnshaw** [comment]
> I think this needs to be its own New topic under Concepts and not just under the API Proxy concept.
> And we may need to list out (bullets) the 3 supported Roles to make them... and then their management context clearer... perhaps even listing the limited menu views that Consumer has.
> And before we are done, we may need to explain that a user can have a different role on each of the teams they are a member of. This part is typically not obvious to new users.

@markbice @robertengaxway I've updated the topic to move roles and teams out to its own section instead of being under API proxy. Also added some placeholder sections for Robert or devs to fill in listing the roles, capabilities, and the explanation about teams.

**Comment by robertengaxway** [comment]
@georgiana-caras You might want add details on the Amplify Central roles and what they can do

**Comment by alexearnshaw** [comment]
@robertengaxway I'm going to comment out the placeholder sections and merge this now, as nobody else other than you can directly edit this PR. @georgiana-caras you will need to make the additions about roles etc in a new PR.

**Comment by robertengaxway** [comment]
@alexearnshaw  I looked at the public docx here: https://docs.axway.com/bundle/axway-open-docs/page/docs/central/fundamental_concepts/index.html

I dont see the merge.

**Comment by alexearnshaw** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!

### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/

### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Comment by alexearnshaw** [comment]
Hi @robertengaxway This one is available on docs.axway.com now - it's an additional manual step I have to do to publish it there.

**Pull request merged**
