### PR TITLE
Update page in pol filter ref section “attributes_retrieve”

### PR DESCRIPTION
**Pull request by sakumar2axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by andreamussap** [comment]
Hi @sakumar2axway 
you must sign in Axway CLA otherwise we can't merge this PR. Please see, https://axway-open-docs.netlify.app/docs/contribution_guidelines/#before-you-start

**Comment by andreamussap** [comment]
> Hi @sakumar2axway
> you must sign in Axway CLA otherwise we can't merge this PR. Please see, https://axway-open-docs.netlify.app/docs/contribution_guidelines/#before-you-start

Hi @sakumar2axway I'm waiting for you to sign in the CLA before I review this pull request. Do you have any question, do you need any help?

**Comment by alexearnshaw** [comment]
@andreamussap This is unblocked now and ready for review. @sakumar2axway contacted me for guidance and has now signed the CLA.

**Comment by alexearnshaw** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
