### PR TITLE
Import of Appcelerator-related guide content

### PR DESCRIPTION
**Pull request by sgtcoolguy**
This is a work in progress PR to investigate the feasibility and progress of exporting our existing wiki guide contents from https://wiki.appcelerator.org/display/guides2/Home into the Open Docs project.

Currently we use a Confluence plugin to export the space as HTML and further convert that through various process to be combined with converted API docs and publish to http://docs.appcelerator.com

I am working on another alternate process which takes the exported HTML and converts to Markdown with docsy frontmatter for this project. This PR let's me see the end results as a live site so I can gauge the gaps/progress.

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@sgtcoolguy Just a suggestion - you might find it quicker to build the site locally rather than having to wait on netlify to build the preview for you each time you change something. You should find everything you need for a local setup in https://axway-open-docs.netlify.com/docs/contribution_guidelines/setup_work_locally/

**Comment by andreamussap** [comment]
Hi Chris (@sgtcoolguy ),
be aware that this pull request was marked as stale and it will be automatically closed if there's no action on it.
/Andrea

**Comment by sgtcoolguy** [comment]
Hey @andreamussap @alexearnshaw I've heard that you are thinking through perhaps re-architecting to handle more products as separate repos/microsites which sounds great to me. Curious how I could help try that out. I assume we'd want to split off our own repo for Appc-related products that I could dump our content into and hook netlify to that. I wasn't sure if you could help set up a repo hooked to netlify that I could use to try it out? I have admin rights in our Appcelerator gtihub org, so I could do our own repo there but we don't have a netlify account (I assume it's paid for/hooked to the Axway org here?)

**Comment by alexearnshaw** [comment]
> Hey @andreamussap @alexearnshaw I've heard that you are thinking through perhaps re-architecting to handle more products as separate repos/microsites which sounds great to me. Curious how I could help try that out. I assume we'd want to split off our own repo for Appc-related products that I could dump our content into and hook netlify to that. I wasn't sure if you could help set up a repo hooked to netlify that I could use to try it out? I have admin rights in our Appcelerator gtihub org, so I could do our own repo there but we don't have a netlify account (I assume it's paid for/hooked to the Axway org here?)

Hi @sgtcoolguy yes indeed this is the plan as having everything in one repo is not sustainable or scaleable. Some high level details of the microsite plan are available here if you have access to Confluence https://techweb.axway.com/confluence/display/RDAPI/Architecture+for+docs+as+code+at+scale ?

The easiest way for you to try this out would be to basically delete all the existing doc content in a fork of our repo, add your own doc content, and then play around with it until you get everything working...

In terms of Netlify, there does not seem to be any link between that account and Axway org, and we can have any number of sites in the Netlify account. As far as I can tell I would need only the Github repo to be able to create a new Netlify site for you.

**Comment by sgtcoolguy** [comment]
> In terms of Netlify, there does not seem to be any link between that account and Axway org, and we can have any number of sites in the Netlify account. As far as I can tell I would need only the Github repo to be able to create a new Netlify site for you.

The repo is at https://github.com/appcelerator/appc-open-docs and I've invited you as an admin

**Comment by alexearnshaw** [comment]
@sgtcoolguy I've added that repo and created a site from it - details sent via Teams. I think we can close this PR now?

**Pull request closed without merging**
