### PR TITLE
Update page in Connect AWS Gateway “deploy-your-agents-1”

### PR DESCRIPTION
**Pull request by sbolosan**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@sbolosan Is there an associated Jira?

**Comment by sbolosan** [comment]
@lbadenhop yes, https://jira.axway.com/browse/APIGOV-16467  thank you.

**Comment by sbolosan** [comment]
@jcollins-axway @kflan-io @dfeldick @vivekschauhan please review

**Review by lbadenhop — APPROVED** [review]

**Review by cbordier — APPROVED** [review]
I approve the changes

**Review by dfeldick — COMMENTED** [review]
approved

**Pull request merged**
