### PR TITLE
RMF-4: Turn goldmark on and fix index page

### PR DESCRIPTION
**Pull request by alexearnshaw**
## Describe the changes

Change the default markdown parser from Blackfriday to Goldmark.

- Change the settings in config.toml
- We must use the unsafe setting for goldmark or the _index.html page does not display correctly (ref https://github.com/google/docsy/issues/205)
- Update the https://axway-open-docs.netlify.app/docs/contribution_guidelines/writing_markdown/ page to replace Blackfriday with Goldmark and to remove the section on nested lists (as no specific guidance on nested lists is needed for Goldmark)

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@andreamussap It seems like this is all we need to do to change to goldmark?

As noted in description, we need to use the goldmark 'unsafe' mode to allow Hugo to build HTML pages like `_index.html` correctly. This would also allow contribs to use HTML within a Markdown page, which could possibly have security implications, however, as our Markdown linter rejects HTML within a Markdown page and does not allow PRs that fail the linter to be merged I think this might be ok or should we check with Scurity team? 

I've tested various random pages and I couldn't find any broken formatting as a result of changing to Goldmark. If you know of any pages with complex formatting such as nested lists etc, let me know and I will test them also.

Also if you let me know which pages often give problems with the CMS changing the formatting, let me know and I'll do some test CMS edits on those page using this preview to see if it helps or not.

**Comment by andreamussap** [comment]
@alexearnshaw (which pages often give problems with the CMS changing the formatting) - from the top of my head I can think of https://axway-open-docs.netlify.app/docs/apim_administration/apiportal_admin/customize_getting_started/ Every time this page is update, CMS messes up with the images between the steps on sections Open ThemeMagic, Create a new theme, Use the new theme.

Another ex: https://axway-open-docs.netlify.app/docs/central/mesh_management/add_env/  Because there's information between the steps, e.g. see section "Deploy the service mesh and Axway mesh agents" every time the page is updated, the CMS changes the formatting of the steps, Usage, Example, inside the steps.

**Comment by andreamussap** [comment]
@alexearnshaw I've opened an issue on Docsy project - '[How to use Goldmark renderer without setting unsafe to true? #323](https://github.com/google/docsy/issues/323)'. Feel free to add any information there in case I missed something. Thanks.

**Comment by alexearnshaw** [comment]
After testing with the changes the CMS makes to the formatting for "Customize API Portal look and feel" page I can confirm that Hugo now displays the page correctly using Goldmark so there will no longer be any need to manually change the formatting back when reviewing a PR.

Page built with Goldmark indents images correctly within lists after CMS makes formatting changes:
image

**Comment by alexearnshaw** [comment]
@andreamussap I've updated the doc and am merging this now :)

**Pull request merged**
