### PR TITLE
APIGOV-18074 - add service update sub command

### PR DESCRIPTION
**Pull request by jcollins-axway**
## Describe the changes

Add new update sub command to the service command for Axway Gateway binary agents

## Deploy preview link

- https://deploy-preview-1868--axway-open-docs.netlify.app/docs/central/connect-api-manager/deploy-your-agents-with-amplify-cli/
- https://deploy-preview-1868--axway-open-docs.netlify.app/docs/central/connect-api-manager/gateway-administation/

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

### CODE REVIEW

**Comment by jcollins-axway** [comment]
@kflan-io @sbolosan @dfeldick @vivekschauhan - when you all have a sec

**Review by dfeldick — APPROVED** [review]

**Review by kflan-io — APPROVED** [review]

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop, please proceed

**Review by cbordier — APPROVED** [review]
I approve the changes.

**Comment by lbadenhop** [comment]
@cbordier can you please look at the formatting of the commands before I merge? The bullets formatting was odd and didn't look right, making each command a heading didn't work because you can't have duplicate headings and bolding the commands on a line of their own didn't work with markdown check. I think the way I finally decided on makes the commands stand out without the formatting looking odd.

**Comment by cbordier** [comment]
@lbadenhop I agree with proposal

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
