### PR TITLE
Update page in Connect API Manager “_index”

### PR DESCRIPTION
**Pull request by cbordier**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by cbordier** [comment]
Hi @lbadenhop
You can review this one.
Cyrille

**Comment by lbadenhop** [comment]
Hi @alexearnshaw and @andreamussap,
The CLA check is in a "Waiting" status. Do you know why? I cannot merge the changes until it passes.

**Comment by alexearnshaw** [comment]
@lbadenhop I've merged this to get around the CLA check issue.

**Comment by lbadenhop** [comment]
Hi @alexearnshaw and @andreamussap -- please upload to docs.axway.com. Thanks.

**Pull request merged**
