### PR TITLE
Update New features and enhancements section on July20 Release Note

### PR DESCRIPTION
**Pull request by jmbermingham**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Passes all status checks
* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Review by GianSchoeman — CHANGES_REQUESTED** [review]
We should remove this part:Technical preview of the 'One User-Multi-Org' capability; In advance of being made available generally in the September 2020 update (7.7.20200930), we are offering a technical preview of the ‘one user belonging to multiple organisations’ capability.

This was only to showcase we had code changes to show, but it is not a feature of the release

**Comment by andreamussap** [comment]
> We should remove this part:Technical preview of the 'One User-Multi-Org' capability; In advance of being made available generally in the September 2020 update (7.7.20200930), we are offering a technical preview of the ‘one user belonging to multiple organisations’ capability. This was only to showcase we had code changes to show, but it is not a feature of the release

Agreed. We don't advertise or make promisses on tech docs. When this feature is available, document it its proper Release Notes.

**Comment by andreamussap** [comment]
@jmbermingham My review is done. Please check https://deploy-preview-1149--axway-open-docs.netlify.app/docs/apim_relnotes/20200730_apimgr_relnotes/#new-features-and-enhancements and let me know if I can merge this PR.

**Comment by jmbermingham** [comment]
Thats looks good to me now.

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
