### PR TITLE
[RDAPI-23542] - Added MySQL 8 driver information

### PR DESCRIPTION
**Pull request by lpinto-axway**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

The existing documentation suggests the use of MySQL connector v5.1.47 when using Maria DB database. However, this version is not compatible with Maria DB but a lower version such as 5.1.29 is. It is also recommended that MySQL 8 is used in conjunction with v5.1.49 of the connector.

## Deploy preview link

https://deploy-preview-1734--axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/system_requirements/
https://deploy-preview-1734--axway-open-docs.netlify.app/docs/apim_installation/apigtw_install/metrics_db_install/

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by lpinto-axway** [comment]
@dmchughaxway can you please let me know if this reads fine or if any more updates are needed? Thanks.

**Review by dmchughaxway — COMMENTED** [review]
I think the things we need to get across are: 
1.	You can use MySQL 8 in the environment but not at the same time as Maria DB
2.	If you do use MySQL 8, by default (because of the entity store configuration), only the 5 series connector will work. You may not use Connector/J 8.0.
3.	If you do need to use MySQL8 and you wish to use Connector/J 8.0, you may do so but to do so you will need to edit the MySQL Driver class name in the JDBC Drivers section of the entity store.  

All of these caveats must be included as a footnote in the supported software PDF maintained by Gilles Ansett.

In relation to the specific bit of text you updated, I think we could reword as follows:

_If you are using MariaDB you must use the MySQL JDBC driver with the MySQL database connection URL (for example, `jdbc:mysql://DB_HOST:3306/reports`). You must also ensure that you are using a MySQL JDBC driver version 5.1.x or earlier (for example, 5.1.29), as the later MySQL JDBC driver versions (Connector/J 8.x) are not compatible with Maria DB._

Then as another note (because the above one is specific to Maria DB) we should say:

_If you are using MySQL8, then you will not be able to use both MySQL and Maria DB databases in the same configuration. For example, use MySQL 8 as the metrics database and Maria DB as the KPS [perhaps you can think of a better example here]. Also, if using MySQL8, by default, only the 5.1.x series of JDBC drivers will work. If wishing to use a later MySQL JDBC driver version (Connector/J 8.x) then the MySQL Driver class name in the JDBC Drivers section of the entity store must be updated from ‘org.gjt.mm.mysql.Driver’ to ‘com.mysql.cj.jdbc.Driver’_

Obviously, we can only make the above statement if we have tested it out successfully. Hope this makes sense. We can chat about it tomorrow in case you have any concerns.

**Comment by cgardineraxway** [comment]
I added deploy preview links to the top conversation here. There are some checkboxes there as well that need to be checked as well by the contributer. Cheers!

**Comment by andreamussap** [comment]
@dmchughaxway are you happy with these changes. Can I start my review?

**Comment by dmchughaxway** [comment]
@andreamussap, yes I am happy with this. Go ahead with your review.

**Comment by andreamussap** [comment]
@lpinto-axway @dmchughaxway FYI about the review: Changes for Axway style and improve readability: 

* Removed duplicated information from 'System requirements' page. In this page, it's enought to say what are the supported databases. We already have there a link to the configuration of DB metrics, where you explain the requirements to use specific's third-party databases.

* Change the Note to a normal paragraph in 'Add third-party JDBC driver files' because the note has grown so much that it's not simply a note anymore.

(@yellabelly @matthewboss-axway @mvenzke-axway Just FYI about important changes in these pages.)

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
