### PR TITLE
RDAPI-22355 - Section describing API Access (Grant Access,  Dependency, and Revoke Access)

### PR DESCRIPTION
**Pull request by JuanAxway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by JuanAxway** [comment]
Preview link https://deploy-preview-1795--axway-open-docs.netlify.app/docs/apim_administration/apimgr_admin/api_mgmt_virtualize_web/#api-access

**Comment by JuanAxway** [comment]
This is a section to describe the new features added to describe the lifecycle of ann API with external access

**Comment by andreamussap** [comment]
@maherb4 @dmchughaxway @credmond-axway before I do my review, I need someone to perform a technical review on the new content/section. If not one of you, then please add someone who can do it. Thank you.

**Review by dmchughaxway — COMMENTED** [review]
Use of term 'external' organization. Is this a term used elsewhere in documentation? Its heavily referenced here but I don't think it resonates from a business perspective. We are trying to describe here how an organization that provides an API can give access to other organizations that wish to consume that API, how they can understand who is using their APIs and how they can revoke access to their apis.

Some spelling issues e.g. once access has **ben** granted.

Link is not rendered correctly - [](https://deploy-preview-1351--axway-open-docs.netlify.app/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles/#organizationadministrator).

Should the API access section be presented before the Perform zero downtime updates to an API section. Does the page here needs to follow the actual life cycle of the API. Something like:
1. Import the backend API
2. Configure security / policies on the API
3. Grant access to the API for consuming organizations
4. Publish the API (not sure if that belongs logically before or after step 3)
5. Approve Subscriptions to the API
6. Upgrade the API when it changes. 
7. Revoke access to the API
8. Deprecate the API
9. Retire the API

The page is kind of like this today but I think we could make it better. 

The section that talks about api access. Is there a typo in end-point name? GET/proxies/{id}/apiacces?

When you say object 1 and object 2 you are describing the response payload for the apiaccess end-point? I feel like perhaps swagger does a better job of this. Would a link to the sample payload and a link to the swagger suffice here? I feel like describing it as object 1 and object 2 is really confusing especially given the fact that those objects are nested. 

If the {id} does not exist, an empty array will be returned. - Maybe small clarification here. This is the id of the API proxy right? So the id that you include as a path parameter. 

If you click on the organization in API Access -> Applications list view where does the link bring you. In order parts of the application where the organization is presented as a link it brings you to the edit organization page. But the user who is accessing this data should not have access to that page right?

Very picky point. Why is there so much space between Organization and Access Granted date?

When we revoke API access to an organization, do we iterate through the applications, determine if any application override quotas for that API were set and delete them? Does that delete cascade to the Quota Counters table?

**Comment by JuanAxway** [comment]
@dmchughaxway The API Access is a separate section, it revolves around the lifecycle of an API used by external organizations, this is a new feature, this is why the name "external organization" is not used elsewhere, it is a new feature.

Thank you for highlighting the spelling issues, this is why Andrea is reviewing the document, she usually makes the necessary corrections when needed, the same with the spacing, when using Netifly, the spacing is a bit of an issue, Andrea usually corrects it as she sees fit in line with Axway's conventions.

No typo in the endpoint, it is GET /proxies/{id}/apiaccess , see AC https://jira.axway.com/browse/RDAPI-15810 further documentation is included in the Swagger page that provides all information on messages, and description.

In relation to your revoke access question, as highlighted in the document, the revoke access is final, whatever quotas or anything else used for that API will be gone, as the external org will not have access to that API anymore, we're talking external access, the actual API and the Organization that owns the API will be unaffected.

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
