### PR TITLE
Improving ModSecurity documentation

### PR DESCRIPTION
**Pull request by cwiechmann**
ModSecurity has changed their documentation structure, by creating documentation-branches for version 2.x (we are using) and version 3.x. Fixed our deep links to work correct again.

### CODE REVIEW

**Comment by cwiechmann** [comment]
I also added some changes + a video how to use CSR Version 3.x, which is requested by customers. This has been described here: https://axway.jiveon.com/thread/30766, but we should make it part of our official documentation.

**Comment by cwiechmann** [comment]
I took me some time to figure out how to disable a single rule. Added the required information how to do that into our documentation.

**Comment by alexearnshaw** [comment]
@cwiechmann Great addition, I've reviewed and made a couple of small changes. It's good to go now from my side, but please give it a quick check over before I merge and publish it. https://deploy-preview-431--axway-open-docs.netlify.com/docs/apim_administration/apigtw_admin/admin_waf/

**Comment by cwiechmann** [comment]
@alexearnshaw, just reviewed and it's great! 

FYI: There might be another PR coming for another typical use-case customers have.
Waiting for an answer here:
https://stackoverflow.com/questions/60373554/modsecurity-is-there-a-way-to-configure-detectiononly-per-rule 
I hope someone can help with that.

**Comment by alexearnshaw** [comment]
> FYI: There might be another PR coming for another typical use-case customers have.
> Waiting for an answer here:
> https://stackoverflow.com/questions/60373554/modsecurity-is-there-a-way-to-configure-detectiononly-per-rule
> I hope someone can help with that.

Great, I'll look out for it!

**Pull request merged**
