### PR TITLE
Added the AMPLIFY Central roles

### PR DESCRIPTION
**Pull request by DesertLeprechaun**
Added the AMPLIFY Central roles

### CODE REVIEW

**Comment by andreamussap** [comment]
Hi @DesertLeprechaun  I've made a small change, please have a look at the preview URL -  https://deploy-preview-598--axway-open-docs.netlify.com/docs/central/fundamental_concepts/#roles-and-teams

I have a question though, what do you mean by '**no Topology or role management**'? Are you referring to [Topology section when adding an environment](https://axway-open-docs.netlify.com/docs/central/add_env/#add-your-environment-to-amplify-central)?

You mean that the Developer role doesn't have access, cannot manage this Topology section? If this is the case I don't think you need to say that because in the 'Add your environment' instructions, the first step is to log in as an Administrator.

**Comment by alexearnshaw** [comment]
Moving to sprint 73 as 72 closing today

**Comment by DesertLeprechaun** [comment]
@andreamussap yes, it makes sense to remove the "no Topology or role management'" statement on Developer role.

**Comment by andreamussap** [comment]
@DesertLeprechaun sorry but I didn't notice this before. The CI check says that **you didn't signed the Axway/CLA**. 

Please have a look at [Before you start](https://axway-open-docs.netlify.com/docs/contribution_guidelines/#before-you-start) and sign the Axway Contributor License Agreement (CLA) otherwise I can't merge this pull request

**Comment by andreamussap** [comment]
@DesertLeprechaun just a kind reminder that you must sign in the Axway CLA, otherwise we can't merge this change.

**Comment by andreamussap** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
