### PR TITLE
[RDAPI-19528] Remove or update references to update-apimanager

### PR DESCRIPTION
**Pull request by JohnD-Axway**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [ x ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ x ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ x ] You have verified the technical accuracy of your change
* [ x ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ x ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by andreamussap** [comment]
@JohnD-Axway Deploy previews: 

* Removed Step 5 - Run update-apimanager

https://deploy-preview-1123--axway-open-docs.netlify.app/docs/apim_installation/apigw_upgrade/upgrade_steps_extcass/#step-5---verify-the-upgrade

* Added information about update-apimanager.py

https://deploy-preview-1123--axway-open-docs.netlify.app/docs/apim_reference/scripts_changelog_sp/#update-apimanagerpy-changes-in-770

* Update Release notes

https://deploy-preview-1123--axway-open-docs.netlify.app/docs/apim_relnotes/20200930_apimgr_relnotes/#removed-features

**Comment by JohnD-Axway** [comment]
@andreamussap I have updated based on your comments in the teams chat.

**Review by andreamussap — APPROVED** [review]

**Comment by andreamussap** [comment]
@JohnD-Axway  I've just made minor changes to 'Run update-apimanager.py script to update API Manager' section, and I'm approving this PR now. Please have a look at [this commit](https://github.com/Axway/axway-open-docs/pull/1123/commits/b1f7caee415e8dc3ce5e36d33592db23928a26e0) and if I got anything wrong please create a new PR for new changes. 

Well done for adding the jira ticket to the title, this is helpful.

**Comment by JohnD-Axway** [comment]
That's great Andrea, thanks!

I think it should be mandated that the ticket ID is added to PRs, we should bring it up in the scrum of scrums.

**Pull request merged**
