### PR TITLE
Manage Environments With CLI

### PR DESCRIPTION
**Pull request by SteveSonoa**
The AMPLIFY CLI will be supporting a full CRUD for managing environments. The CLI will be rapidly expanding to eventually handle all commands supported by AMPLIFY Central's web UI, and the documentation will need to be created & updated with a standard format.

Reference: https://techweb.axway.com/jira/browse/APIGOV-12373

### CODE REVIEW

**Comment by robertengaxway** [comment]
@SteveSonoa Steve, can we make a reference to the "ReadMe" file on NPM?   Something like "For the latest CLI commands, refer to the ReadMe.MD file on NPM"

**Comment by markbice** [comment]
We should also indicate the min central plugin value required to use this new functionality.  We show it, but current customers need a hint when they should upgrade to get it.  Some addtl comment/note at the top after step 4 in the Install AMPLIFY CLI section

**Comment by markbice** [comment]
The Environment Management first sentence should be changed to say:

AMPLIFY Central allows users to manage their distributed cloud and OnPrem environments using the CLI.

**Comment by SteveSonoa** [comment]
@markbice I've updated both issues; thank you for the comments.

**Comment by alexearnshaw** [comment]
@SteveSonoa I will review and merge this shortly, but after an initial look, I'd propose not having a completely separate topic for this but instead merging it with the [Manage proxy topic](https://axway-open-docs.netlify.com/docs/central/cli_proxy_flow/). This way we'd eliminate the duplication of the first few preparatory sections (Before you start through to Log in to CLI) and have a single CLI topic with the following outline:

- Preparatory sections (Before you start through to Log in to CLI)
- Manage an API proxy
-- Create API config file
-- Create proxy
-- Promote proxy
-- Test proxy
- Manage an environment
-- Create env
-- List envs
-- Get env details

I'm happy to do this restructuring when reviewing the topic, if you have no objections or any reasons why we shouldn't take this approach?

**Comment by robertengaxway** [comment]
@alexearnshaw  Just something to consider, I would expect the number of CLI commands to grow.   In that scenario, will the CLI chapter will be linked to the UI equivalent dcos?   Or should both UI and CLI be covered in the same topic such as "Manage Environments".

**Comment by alexearnshaw** [comment]
> @alexearnshaw Just something to consider, I would expect the number of CLI commands to grow. In that scenario, will the CLI chapter will be linked to the UI equivalent dcos? Or should both UI and CLI be covered in the same topic such as "Manage Environments".

@robertengaxway I may be wrong but wouldn't the typical users of CLI be different to those using UI, in which case I don't think there's any need to link them or have them covered in same doc? My understanding is that UI is really for demo/dev envs and the CLI/APIs for production/real use, hence why we have an API first strategy?

**Comment by robertengaxway** [comment]
@alexearnshaw I am not advocating for any particular way to structure the docs.  The recommendation is to keep the UI in a different chapter/section than CLI/API in the docs if I understand correctly.

**Comment by SteveSonoa** [comment]
@robertengaxway @alexearnshaw I'm open to having a conversation about this. We initially discussed what would be the best way to move forward with this (how to organize CLI commands with Web UI directions), and with the growing list of commands and growing complexity of CLI options, we wanted it to be in a different location.

We also believe CLI customers shouldn't be asked to scroll to the bottom of a page to find what they're looking for 100% of the time. Between those ideas, it was initially decided to have a separate section (and, as you can see, there is already a separate section for the existing CLI command).

We can discuss best practices more (and I welcome it). Just wanted to give you the thought process we've had up to this point.

**Comment by SteveSonoa** [comment]
@robertengaxway @alexearnshaw @markbice Are there any other updates or conversations about this? Are we okay to merge this branch, or do we need additional changes? Other Documentation stories are looking to build on this, so I'd like to get it completed if there's a general consensus that we're ready to do so.

I would also mention that this is the starting point of an iterative process. It's a foundation, not an exhaustive & complete solution yet.

**Comment by robertengaxway** [comment]
I have no objections to merging.  The goal was to introduce the interactive CLI enhancements and this is a good start.

**Comment by alexearnshaw** [comment]
@SteveSonoa @robertengaxway I can't merge this without restructuring it to remove the duplication of the **6** common sections between this and the manage proxies topic. Having such duplication will require maintaining the same information in 2 different topics, and from past experience I know that this will result in one of the topics ending up incorrect and outdated, resulting in incorrect doc that is of no value to customers. I can restructure as suggested above, or if we are concerned with scrolling and the CLI doc is going to grow quickly, then I can split it into 3 different topics:
1. Get started with CLI (the 6 common prep steps)
2. Manage proxies with CLI
3. Manage environments with CLI

I've no issue with keeping CLI instructions separate from UI instructions, but I don't see how that discussion is relevant to this particular PR...my objections and suggestions are solely around removing duplication of content so that we can keep the doc easily maintainable and correct.

**Comment by robertengaxway** [comment]
Feel free to restructure as you recommend.  I like the idea of focused CLI topics.    Would it make sense to make the "Manage Environments with CLI" topic 2 and "Manage Proxies with CLI" topic 3.   Largest scope is Environments, then we will likely introduce Services/Proxies, followed by Policies.

**Comment by alexearnshaw** [comment]
Thanks @robertengaxway I hope to get to this first thing tomorrow, should be merged by end of that day.

**Comment by alexearnshaw** [comment]
@SteveSonoa @robertengaxway This is done and ready to merge, please check the 3 new topics:
https://deploy-preview-177--axway-open-docs.netlify.com/docs/central/cli_getstarted/
https://deploy-preview-177--axway-open-docs.netlify.com/docs/central/cli_proxy_flow/
https://deploy-preview-177--axway-open-docs.netlify.com/docs/central/cli_environments/

Robert I left proxies as topic 2 and env as topic 3 for now, but we can change the order later when the env topic grows.

Steve, how will we know when to remove the note "This feature is currently in development and will be available soon." or should I remove it now?

**Comment by SteveSonoa** [comment]
@alexearnshaw Please do not remove that alert now. We are currently developing the CLI, and my understanding is that it's currently only available for our preprod environments. Our team will be removing this alert when the feature becomes available to customers to use. @robertengaxway is extremely good at making sure we stay on top of the Documentation for this!

**Comment by alexearnshaw** [comment]
Thanks @SteveSonoa merging now with the note included.

**Comment by alexearnshaw** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
