### PR TITLE
Create page in Connect API Manager “security-concerns”

### PR DESCRIPTION
**Pull request by cbordier**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by cbordier** [comment]
@lbadenhop 
Ready for review. The TLS/SSL page needs to be a sub-page of that one now if possible.
I don't know how to set up some link. Can you please add them: all the one mark with Refer to...
Cyrille

**Comment by cbordier** [comment]
Hi @lbadenhop 
I forget to add this line in the Data exchanged / Discovery Agent.

There is a variable configuration to select which API should be send to AMPLIFY platform: `apimanager.filter`. Only the matching APIs will be transfer to AMPLIFY platform. Refer to Filtering APIs to be discovered section.
The Discovery Agent sends the following information....

**Comment by lbadenhop** [comment]
Hi @alexearnshaw and @andreamussap. Please upload to docs.axway.com.

**Comment by andreamussap** [comment]
> Hi @alexearnshaw and @andreamussap. Please upload to docs.axway.com.

@lbadenhop This is done.

**Pull request merged**
