### PR TITLE
APIGOV-16534 - Update page in Connected agent - Common reference “trace_redaction”

### PR DESCRIPTION
**Pull request by jcollins-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by jcollins-axway** [comment]
@sbolosan @dfeldick @vivekschauhan @kflan-io - please review for content

**Review by kflan-io — APPROVED** [review]

**Comment by jcollins-axway** [comment]
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connected_agent_common_reference/trace_redaction/
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-api-manager/agent-variables/
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-api-manager/tips-troubleshooting-and-limitations/
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-aws-gateway/deploy-your-agents-1/
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-aws-gateway/tips-and-troubleshooting/
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-azure-gateway/agent-variables/
https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-azure-gateway/agent-variables/

**Review by sbolosan — APPROVED** [review]

**Comment by cbordier** [comment]
@jcollins-axway.
Several issues:

- https://deploy-preview-1780--axway-open-docs.netlify.app/docs/central/connect-api-manager/agent-variables/ is not accessible... Looks like it has been removed
-  Azure agent variable: missing TRACEABILITY_REDACTION_PATH_SHOW

**Review by sbolosan — APPROVED** [review]

**Review by dfeldick — APPROVED** [review]

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop, please proceed.

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
