### PR TITLE
RDAPI-18049 Add Multi Organization capabilities for a single user

### PR DESCRIPTION
**Pull request by JuanAxway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by andreamussap** [comment]
@JuanAxway thank you for this contribution, but the only new information in this PR, is a new section: 

> **Multi Organization capabilities for a single user**
> If a user belogs to more than one organization, a dropdown option will appear in the home screen, giving the user the option to swicth organizations with a simple click

However, it seems incomplete, not really helpful to customers. We need to discuss more what we want to document about the multi-org and where (this page, a new page). Therefore, I'm closing this PR.

**Comment by JuanAxway** [comment]
@andreamussap Yes, I have just changed the order of user roles to ensure the 3 user roles are specified in order of importance. The landing page is the new feature that I can expand in greater detail if you want me to, this new feature is simple and convenient, you just click in an arrow bellow your name and a list will appear to toggle in between orgs with one click. I am releasing a demo explaining it which will be published to the public.

**Comment by maherb4** [comment]
Yes to explain the multi org functionality we should document everything from how to create a user in multi orgs and the explanation of the org switch menu in the landing land.
We could also link to the video created in https://jira.axway.com/browse/RDAPI-21646

**Comment by andreamussap** [comment]
> @andreamussap Yes, I have just changed the order of user roles to ensure the 3 user roles are specified in order of importance...

@JuanAxway I can accept this change, but the 'Multi Organization capabilities for a single user' section, the way it is, it's not helpful. 
When we have a proper page explaining the multi org, we can then put a small section here (if this makes sense, we'll have to review this) linking to the new page. But, at this moment, there's no need for that. Thanks.

**Review by andreamussap — APPROVED** [review]
https://deploy-preview-1155--axway-open-docs.netlify.app/docs/api_mgmt_overview/key_concepts/api_mgmt_orgs_roles/#api-manager-access-control

**Pull request merged**
