### PR TITLE
Update page in Connect API Manager “security-concerns”

### PR DESCRIPTION
**Pull request by cbordier**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by cbordier** [comment]
Hi @lbadenhop 
Can you review?
Be careful with the url I changed. It seems the preview is not good
Cyrille

**Comment by lbadenhop** [comment]
@alexearnshaw 
Markdown checks are returning MD034/no-bare-urls on line 15 and 16; however, Cyrille has verified that these should not be active links (only references) and are coded correctly. I cannot merge with master until the check runs successfully. Do you have a workaround?

**Comment by alexearnshaw** [comment]
> @alexearnshaw
> Markdown checks are returning MD034/no-bare-urls on line 15 and 16; however, Cyrille has verified that these should not be active links (only references) and are coded correctly. I cannot merge with master until the check runs successfully. Do you have a workaround?

Hi @lbadenhop @cbordier The way to avoid MD errors for those lines is to use backticks around the URLs so that they are seen as code instead of URLs.

**Comment by lbadenhop** [comment]
Hi @alexearnshaw and @andreamussap. Please upload to docs.axway.com.

**Pull request merged**
