### PR TITLE
Update page in Connect API Manager “gateway-administation”

### PR DESCRIPTION
**Pull request by jcollins-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by jcollins-axway** [comment]
Jira - APIGOV-16444

**Comment by jcollins-axway** [comment]
@sbolosan @dfeldick @kflan-io @vivekschauhan - please review

**Review by dfeldick — APPROVED** [review]

**Review by cbordier — APPROVED** [review]
I approve the changes
@lbadenhop, please proceed.

**Review by sbolosan — APPROVED** [review]

**Review by lbadenhop — APPROVED** [review]

**Comment by andreamussap** [comment]
> Jira - APIGOV-16444

@jcollins-axway this is more helpful if you add it to the title of your PR. For more information, see https://axway.jiveon.com/groups/api-mgt/blog/2020/10/12/axway-open-docs-contributing-via-github

**Pull request merged**
