### PR TITLE
Update page in AMPLIFY Central section “feauth_oauth”

### PR DESCRIPTION
**Pull request by JohnD-Axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by JohnD-Axway** [comment]
@alexearnshaw  The info in that commit is pertinent to FE OAuth. I'm not sure it's covered anywhere else in the doc.

**Comment by alexearnshaw** [comment]
Ah sorry @JohnD-Axway I just bulk-closed all the PRs from the workshop. Re-opening this one :)

**Comment by alexearnshaw** [comment]
@JohnD-Axway I noticed a few other missed style issues in the doc while reviewing your change (unnecessary capitalization etc). Can you give it a quick check over before I merge to make sure I didn't change/remove anything essential? Thanks!

**Comment by JohnD-Axway** [comment]
> @JohnD-Axway I noticed a few other missed style issues in the doc while reviewing your change (unnecessary capitalization etc). Can you give it a quick check over before I merge to make sure I didn't change/remove anything essential? Thanks!

Updates look good to me Alex, thanks.

**Comment by alexearnshaw** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
