### PR TITLE
Create page in AMPLIFY Release notes section “amplify-central-november-2020-release-notes”

### PR DESCRIPTION
**Pull request by lbadenhop**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by lbadenhop** [comment]
@cbordier Ready for review

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop you can merge it.
But deployment should be done November 30th

**Comment by lbadenhop** [comment]
@cbordier I cannot merge until the Release Notes are ready to upload. If I merge now, uploads performed between now and November 30th would automatically upload the Release Notes. Uploads are an "All or Nothing," meaning we cannot cherry pick what is uploaded -- if it's merged, it's uploaded.

**Comment by cbordier** [comment]
@lbadenhop , that's OK for me.

**Review by cbordier — APPROVED** [review]
I approved the changes

**Pull request merged**
