### PR TITLE
RDAPI-26796 Removing alert about FIPS mode not being supported as it has been re-introduced

### PR DESCRIPTION
**Pull request by scormicanAxway**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Removing alert about FIPS mode not being supported as it has been re-introduced and removed the togglefips ref for Windows as it is no longer supported.

## Deploy preview link

https://deploy-preview-2388--axway-open-docs.netlify.app/docs/apim_administration/apigtw_admin/admin_fips/

### CODE REVIEW

**Comment by andreamussap** [comment]
I know this is still a WIP, but there's something wrong with it. Look at the list of commits - probably because you started from `developaug22`, then changed to `master` ?

**Comment by scormicanAxway** [comment]
@andreamussap yeah, same as last time I tried to create a merge request, the default branch was master, not developaug22, changed to correct base branch

**Comment by andreamussap** [comment]
@JohnD-Axway @scormicanAxway I believe this reintroduction of FIPS mode support should be mentioned in the release notes page??

Do you want to update the release notes at once, under this very pull request?

**Comment by scormicanAxway** [comment]
@andreamussap There's an additional ticket to cover that, I'll repurpose/rename this one to use that ticket number instead RDAPI-26798, I'll delete this merge request.
Cc: @JohnD-Axway

**Pull request closed without merging**
