### PR TITLE
Update page in Connect AWS Gateway “cloud-administration-operation”

### PR DESCRIPTION
**Pull request by jcollins-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by jcollins-axway** [comment]
@dfeldick @kflan-io @sbolosan @vivekschauhan  - please review

**Comment by jcollins-axway** [comment]
JIRA APIGOV-16329

**Review by dfeldick — APPROVED** [review]

**Review by dfeldick — APPROVED** [review]

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop, please proceed.

**Comment by jcollins-axway** [comment]
@cbordier - thank you for fixing the markdown errors

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
