### PR TITLE
RDAPI-29068 - Added description of new configuration parameters, supporting SSL, added for apigw-backup-tool. removed details and sample scripts for manual backup & restore.

### PR DESCRIPTION
**Pull request by credmond-axway**
## RDAPI-29068

The apigw-backup-tool now supports SSL enabled Cassandra environments. New configuration parameters have been added. This documentation change simply describes those new parameters. 

## RDAPI-29136

Removed details and sample scripts for manual backup & restore of Cassandra keyspaces

**Deleted sections** 

- Use cqlsh to back up a keyspace schema
- Back up a keyspace manually
- Sample Cassandra snapshot backup script
- Restore a keyspace schema manually
- Restore API Management and KPS keyspaces manually
- Sample Cassandra restore snapshot script
- Sample Cassandra reload the indexes script

## Deploy preview 
http://pr-2555.axway-open-docs.opendocs-builder.pcloud.axway.int/docs/cass_admin/cassandra_bur/index.html

### CODE REVIEW

**Comment by docsbuilder** [comment]
### <span aria-hidden="true">✅</span> Deploy preview is ready!

 |  Name | Link |
 |---------------------------------|------------------------|
 |<span aria-hidden="true">🔨</span> Latest commit | dcc6cf0 |
 |<span aria-hidden="true">😎</span> Deploy preview | http://PR-2555.axway-open-docs.opendocs-builder.pcloud.axway.int |

**Comment by andreamussap** [comment]
@mmilner-axway @mvenzke-axway Just FYI.

**Comment by mvenzke-axway** [comment]
@andreamussap Remembering Jim's discussion in "customer pain points" the prior version of this doc is going to be one we want to save.  While the deleted info is not stuff we want to maintain given this tool, it's going to still have considerable interest.

**Comment by andreamussap** [comment]
> @andreamussap Remembering Jim's discussion in "customer pain points" 

Thanks, @mvenzke-axway See comments on RDAPI-29136

**Pull request merged**
