### PR TITLE
APIGOV-15487 - Update page in Connect API Manager “_index”

### PR DESCRIPTION
**Pull request by cbordier**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by cbordier** [comment]
I am not fan of my title: Going farther... Maybe Further reading or something like this would be better.
@lbadenhop , can you review and proceed.

**Comment by lbadenhop** [comment]
@cbordier  I changed "Going farther" and committed the changes, but now this is stuck at the cla check. Can you preview the changes and then make a small change, commit and see if it passes the cla check for you?

**Comment by lbadenhop** [comment]
@andreamussap Can you please bypass the CLA check and merge the changes? Per @cbordier, this file must be merged before #1121. Thanks

**Comment by lbadenhop** [comment]
Closing this pull request per Cyrille. The changes from this PR were incorporated into #1121.

**Pull request closed without merging**
