### PR TITLE
APIGOV-12428 AMPLIFY Central CFT Profile Documentation

### PR DESCRIPTION
**Pull request by SteveSonoa**
Documentation for CFT Profile CRUD in Apps in AMPLIFY Central. Includes documentation and images.

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@andreamussap Can you review this PR for Steve please? Only the topic cft_profile.md needs review - the other topics were already merged under PR #177 (not sure why they show in this diff)

**Comment by SteveSonoa** [comment]
@alexearnshaw @andreamussap I'm seeing that the public portal of this page requires a login. I don't believe this is correct, but I'm not sure what would have caused it. https://docs.axway.com/bundle/axway-open-docs/page/docs/central/cft_profile/index.html

**Comment by andreamussap** [comment]
@SteveSonoa same for me, even to access the 'classic' API Management docs. This is not related to AMPLIFY Central docs... I believe it's an issue with the portal in production. It was very slow a few min ago, and now not even loading. I'll ping Paul Lorentz and ask him to check.

**Comment by andreamussap** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
