### PR TITLE
RDAPI-23307 Add JWT Verify Filter payload claim validate policy

### PR DESCRIPTION
**Pull request by dsantosaxway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by dsantosaxway** [comment]
@JuanAxway please review!

**Comment by dsantosaxway** [comment]
## Deploy preview link

https://deploy-preview-1689--axway-open-docs.netlify.app/docs/apim_policydev/apigw_polref/integrity_additional/#jwtverify-filter

**Review by JuanAxway — APPROVED** [review]

**Comment by JohnD-Axway** [comment]
@dsantosaxway you should rebase on developmar21 to get the latest changes.
We have grouped each tab under it's own sub heading, this content should be under a heading for the "Advanced" Tab.

**Comment by dsantosaxway** [comment]
> @dsantosaxway you should rebase on developmar21 to get the latest changes.
> We have grouped each tab under it's own sub heading, this content should be under a heading for the "Advanced" Tab.

**Comment by dsantosaxway** [comment]
@JohnD-Axway Done as requested. Could you please review

**Review by JuanAxway — APPROVED** [review]

**Review by andreamussap — APPROVED** [review]

**Pull request merged**
