### PR TITLE
Added swagger promote link

### PR DESCRIPTION
**Pull request by cwiechmann**
Swagger-Promote is a great way to automate the API-Manager. It's already successfully used by a lot customers and so we should make it part of the documentation, so that all customer know about it.

@maherb4, perhaps you can confirm if this is okay for you.

### CODE REVIEW

**Comment by cwiechmann** [comment]
@alexearnshaw, The detailed information is written on the Swagger-Promote website directly, hence I was thinking everybody could review it there to understand it. Of course, I can add a few more words directly in our documentation if you believe that makes sense. 
If yes, should I add this directly as part of the bullet-point list (where the link is placed right now) or somewhere else?

**Comment by alexearnshaw** [comment]
> @alexearnshaw, The detailed information is written on the Swagger-Promote website directly, hence I was thinking everybody could review it there to understand it. Of course, I can add a few more words directly in our documentation if you believe that makes sense.
> If yes, should I add this directly as part of the bullet-point list (where the link is placed right now) or somewhere else?

@cwiechmann yes I think just one sentence giving a bit more context would be great. That way users will have a better idea of whether the website link is of interest to them. An additional sentence in the same bullet item would be fine.

**Comment by alexearnshaw** [comment]
@cwiechmann Thanks for the update. After thinking about it a bit more I decided to pull this out to a Tip instead of having it mixed in with the other bullets. I'll go ahead and merge it now.

**Comment by cwiechmann** [comment]
@alexearnshaw, looks good to me. Thanks!

**Pull request merged**
