### PR TITLE
Connect dataplanes minor changes

### PR DESCRIPTION
**Pull request by cwiechmann**
## Describe the changes

I'm working on to test/try the functionality to connect the data-planes (AWS-API Gateway & Axway API-Management) to AMPLIFY-Central.  
This PR includes everything I realized as confusing, unclear, etc. 

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Follows [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)
* [ ] Follows [best practices](https://axway-open-docs.netlify.com/docs/contribution_guidelines/bestpracticedevdoc/)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links
* [ ] Is discoverable and navigable

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a size label (unless this work is tracked in the ReadMeFirst JIRA project)
* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added it to the correct Sprint milestone
* [ ] You have appended a `fixes` line to this description if this PR fixes a specific GitHub issue
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new AMPC topics)

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@cwiechmann This is currently marked as draft so just checking if it's ready for review?

@lbadenhop @cbordier This has been assigned to you both for review so just making sure you are aware of it :)

**Comment by cwiechmann** [comment]
@alexearnshaw, Yes, that is correct at the moment. Waiting for more information / input on how to setup everything.

**Comment by lbadenhop** [comment]
@alexearnshaw  Yes, I received the notification yesterday. Thanks for checking.

**Comment by lbadenhop** [comment]
@cwiechmann Verifying that this should still be marked as draft.

**Comment by cwiechmann** [comment]
Thanks for asking @lbadenhop. Yes, it's still draft, however today I made some progress with that. Final step is to record a short video showcasing what is possible now and include it in the docs.

**Comment by cwiechmann** [comment]
@andreamussap, @cbordier, @lbadenhop 
This PR is basically the result of my work to connect an Axway V7 API-Gateway to AMPLIFY Central. Everything, that was unclear or not precise enough IMHO is now part of this PR to get this improved. 
Once this documentation is ready I'm going to share it with the client.

Please let me know, if you have any questions or if some of the changes are unclear.

**Comment by lbadenhop** [comment]
Hi @andreamussap, as the code owner of two edited topics, please approve the changes. These changes can then be merged with master and upload to docs.axway.com. Thanks.

**Comment by andreamussap** [comment]
I only reviewed content/en/docs/central/cli_central/cli_install.md and content/en/docs/central/mesh_management/add_env.md pages.

@cwiechmann  please have a look at my changes (commits below) and if I got anything wrong you can edit the page and create a new, small PR for more changes.

- https://github.com/Axway/axway-open-docs/pull/892/commits/320c6c74ef8f375fbbd0dbfd91832d4fe3aee9e9
- https://github.com/Axway/axway-open-docs/pull/892/commits/a85a6d7f68cbbdbb170f152359a6522d9d155448

This is available on Netlify now, and will be available on Zoomin shortly.

**Pull request merged**
