### PR TITLE
Update page in Connect API Manager “gateway-administation”

### PR DESCRIPTION
**Pull request by sbolosan**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by sbolosan** [comment]
jira ticket - https://jira.axway.com/browse/APIGOV-16449

**Comment by sbolosan** [comment]
@kflan-io @dfeldick @jcollins-axway please review... how this got past you guys the first time, I do not know.  I did it on purpose and no one passed =)

**Review by kflan-io — APPROVED** [review]

**Review by dfeldick — APPROVED** [review]

**Review by jcollins-axway — APPROVED** [review]

**Comment by sbolosan** [comment]
@cbordier looks good.

**Review by cbordier — APPROVED** [review]
I approve the changes.
@lbadenhop, please proceed.

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
