### PR TITLE
WIP: Update API Portal administration “customize_APICatalog_overview”

### PR DESCRIPTION
**Pull request by ygeorgiev-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by alexearnshaw** [comment]
@ygeorgiev-axway Is this ready for review or are you still making changes?

**Comment by ygeorgiev-axway** [comment]
> @ygeorgiev-axway Is this ready for review or are you still making changes?

I am ready.

**Comment by alexearnshaw** [comment]
@ygeorgiev-axway I didn't get to this today, sorry. Will do Monday.

**Comment by ygeorgiev-axway** [comment]
@alexearnshaw John's taking a look at the changes, so let's wait for his feedback before merging it. I'll ping you when he's ready.

**Comment by ygeorgiev-axway** [comment]
@alexearnshaw we are ready to merge.

**Comment by ygeorgiev-axway** [comment]
@alexearnshaw looks great! thanks!

**Comment by alexearnshaw** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
