### PR TITLE
DRAFT - RDAPI-18479 Update page in APIM release note section “20210130_apimgr_relnotes”

### PR DESCRIPTION
**Pull request by credmond-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by credmond-axway** [comment]
@kmercierwhite @JuanAxway Short update for the release note. Please review.

Preview: [https://deploy-preview-1577--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/#api-manager-request-rate-limiter](https://deploy-preview-1577--axway-open-docs.netlify.app/docs/apim_relnotes/20210130_apimgr_relnotes/#api-manager-request-rate-limiter)

**Review by JuanAxway — APPROVED** [review]

**Review by JuanAxway — APPROVED** [review]

**Review by kmercierwhite — APPROVED** [review]

**Comment by kmercierwhite** [comment]
This change will need to be applied to the development branch for March21

**Comment by andreamussap** [comment]
> This change will need to be applied to the development branch for March21

@kmercierwhite In this case, please close this PR. As you can see below the list of checks, there's a conflict in the branch - I don't even know why, but there's not point in leaving the PR waiting until March because things might change until there, and this will create even more conflicts. Thanks.

**Comment by credmond-axway** [comment]
Closing this ticket as this feature has been moved to Mar21. I will create a new PR for Mar21 release note.

**Pull request closed without merging**
