### PR TITLE
APIGOV-16492 - Update page in Connect AWS Gateway “agent-security-aws”

### PR DESCRIPTION
**Pull request by vivekschauhan**
Automatically generated by Netlify CMS

### CODE REVIEW

**Review by jcollins-axway — APPROVED** [review]

**Comment by vivekschauhan** [comment]
@dfeldick,  @jcollins-axway , @sbolosan , @kflan-io, please review

**Review by dfeldick — APPROVED** [review]

**Review by sbolosan — APPROVED** [review]

**Review by kflan-io — APPROVED** [review]

**Review by lbadenhop — APPROVED** [review]

**Comment by lbadenhop** [comment]
@vivekschauhan Since this is AWS, do you want the link in your new edit to be going to API Manager?

**Comment by vivekschauhan** [comment]
> @vivekschauhan Since this is AWS, do you want the link in your new edit to be going to API Manager?

The link has always been pointing to the agent variables in connect-api-manager. I guess there is no agent-variables in aws

**Comment by lbadenhop** [comment]
@vivekschauhan No, the topic that has the variables is Deploy your agents - advanced functionality.

**Comment by lbadenhop** [comment]
@vivekschauhan @cbordier Almost every link in this topic points to API Manager topics, not AWS topics.

**Comment by lbadenhop** [comment]
@vivekschauhan @Cyrille Let me know if it's ok that I change all the links in this topic.

**Comment by lbadenhop** [comment]
@cbordier I will change the links in this topic and then notify you for review once I'm done.

**Review by cbordier — COMMENTED** [review]
approved

**Pull request merged**
