### PR TITLE
RDAPI-24557 Manage KPS editorial and formatting updates

### PR DESCRIPTION
**Pull request by andreamussap**
https://deploy-preview-1967--axway-open-docs.netlify.app/docs/apim_policydev/apigw_kps/how_to_use_kpsadmin_command/#examples-of-kpsadmin-scriptable-commands

### CODE REVIEW

**Comment by andreamussap** [comment]
@dshielaxway I've reformatted section 'Examples of kpsadmin scriptable commands' because it was unnecessarily cluttered IMO. There's no need, in fact doesn't make sense to have headings for examples, which are 1 sentence and 1 command. But, before I merge this can you please confirm that this is ok, of if there's some issue with this change? Thanks.

**Comment by andreamussap** [comment]
@dshielaxway There's this note on the page - "_kpsadmin requires you to specify an API Gateway in a group. This is known as the KPS Admin API Gateway, which fields KPS requests only._" - and I can't make sense of "_which fields KPS requests only_"!?? 

Is this accurate?

**Comment by dshielaxway** [comment]
> @dshielaxway I've reformatted section 'Examples of kpsadmin scriptable commands' because it was unnecessarily cluttered IMO. There's no need, in fact doesn't make sense to have headings for examples, which are 1 sentence and 1 command. But, before I merge this can you please confirm that this is ok, of if there's some issue with this change? Thanks.

Hi Andrea,

Personally I think having the headings was better because it was easier, at a glance, to find a specific command, whereas now your eye is drawn to 'General operations' and you have to read more to find what you're looking for, or manually search the page. At the very least there should be some sort of separation between the commands, whether that be a horizontal rule, or an additional blank line so as to group the text pertaining to each command.

**Comment by dshielaxway** [comment]
> @dshielaxway There's this note on the page - "_kpsadmin requires you to specify an API Gateway in a group. This is known as the KPS Admin API Gateway, which fields KPS requests only._" - and I can't make sense of "_which fields KPS requests only_"!??
> 
> Is this accurate?

Hi Andrea,

The word 'fields' in this context means to handle. Perhaps using the verb 'services' (or 'processes') would clear up any confusion.

**Comment by andreamussap** [comment]
> Personally I think having the headings was better because it was easier, at a glance, to find a specific command, whereas now your eye is drawn to 'General operations' and you have to read more to find what you're looking for, or manually search the page. At the very least there should be some sort of separation between the commands, whether that be a horizontal rule, or an additional blank line so as to group the text pertaining to each command.
> 
> There's also a typo in the following sentence:
> 'This command drops the table and recreate an empty table. All data is lost.'
> It should be 'This command drops the table and recreates an empty table. All data is lost.'

@dshielaxway I understand. I've put them back. Thanks for the fback!

**Pull request merged**
