### PR TITLE
Create page in APIP admin section “connect-api-portal-to-api-central”

### PR DESCRIPTION
**Pull request by astoyanovAxway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by andreamussap** [comment]
@astoyanovAxway is this work in progress?

**Comment by astoyanovAxway** [comment]
Yes, this is work in progress

**Comment by andreamussap** [comment]
> Yes, this is work in progress

@astoyanovAxway please let me know if this is ready for review

**Comment by dginevaAxway** [comment]
@andreamussap looks good to me!

**Comment by andreamussap** [comment]
Title '_Connect API Portal to API Central_' is not meaningful. As a user, why would I want to connect these two applications? 
So, I've changed the title to 'Expose APIs published from the Unified Catalog', so when the user sees the title they will have an idea of what this topic is about. But if you have a better suggestion let me know. (@astoyanovAxway @dginevaAxway )

Also changed the file name from 'connect-api-portal-to-api-central' to 'expose_APIs_published_from_catalog'.

**Comment by astoyanovAxway** [comment]
@andreamussap , I agree with your comment, but it is not only APIs that are exposed but also Applications and subscriptions from API Central, so I suggest - " Configure API Portal to expose resources from Unified Catalog "

**Pull request merged**
