### PR TITLE
[RDAPI-23715] SSO users in API Manager are not logged out when logging out of API Portal

### PR DESCRIPTION
**Pull request by dsantosaxway**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

When you log out from api portal, api manager session remains active. This is the new expected behaviour

## Deploy preview link

https://deploy-preview-2206--axway-open-docs.netlify.app/docs/apim_administration/apiportal_sso/#logout-sequence

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [x] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Review by kmercierwhite — CHANGES_REQUESTED** [review]
Step 4 in the original document needs to stay too.

**Comment by dsantosaxway** [comment]
> Step 4 in the original document needs to stay too.

Done! Thanks @kmercierwhite

**Review by kmercierwhite — CHANGES_REQUESTED** [review]
Sorry Diogo, but I think these are in the incorrect order now. It should go:

IDP removes session, returns saml logout response
Browser post the saml logout response
Portal redirects to logout

**Review by kmercierwhite — APPROVED** [review]

**Comment by andreamussap** [comment]
Since this is API documentation, @dginevaAxway would you like to review the changes before I merge it?

**Comment by dginevaAxway** [comment]
seems ok for API Portal

**Pull request merged**
