### PR TITLE
Open doc changes for adding new prompt of new k8s cluster

### PR DESCRIPTION
**Pull request by ms8527**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

Enter a brief description of your changes to communicate to the reviewers what you changed and why.

## Deploy preview link

Please add the deploy preview link to the **specific page** that you've changed.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [ ] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [ ] You have signed the [Axway CLA](https://cla.axway.com/)
* [ ] You have verified the technical accuracy of your change
* [ ] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [ ] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [ ] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Review by markbice — APPROVED** [review]
I approve the content changes for this update. @lisa, do we need to eventually change the name on the .md file so that it removes the "amplify" and replaces it with "axway" also in the /md name and generated path?

**Comment by lisa** [comment]
> I approve the content changes for this update. @lisa, do we need to eventually change the name on the .md file so that it removes the "amplify" and replaces it with "axway" also in the /md name and generated path?

@markbice I believe you mean a different Lisa than myself.

**Comment by lbadenhop** [comment]
@markbice Changing amplify to axway in the filename (.md) is not a simple change, as it could potentially break links. Can we have a quick meeting sometime this week on how to track the work?

**Comment by markbice** [comment]
yes, renaming can wait until we do a more exhaustive review and change.  Let's release this smaller update as is.

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
