### PR TITLE
[RDAPI-14603] Security response headers.

### PR DESCRIPTION
**Pull request by sgoka-axway**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by sgoka-axway** [comment]
Please review.
https://deploy-preview-1838--axway-open-docs.netlify.app/docs/apimgmt_security/c_secgd_config_secconfig/

**Comment by andreamussap** [comment]
Ongoing discussion under RDAPI-14603

**Comment by sgoka-axway** [comment]
Created another pull request using local environment

**Comment by mvenzke-axway** [comment]
We should add the removed info on the CSP header from https://github.com/Axway/axway-open-docs/pull/1835/ here, namely this -

===

You can configure the CSP header for both API Gateway and API Manager. To set the header, you must update the product's Java properties file, `envSettings.props`, which is available in the following locations:

* For API Gateway, set the variable `env.MANAGEMENT.CONTENTSECURITYPOLICY`, in the `apigateway/conf/envSettings.props` file.
* For API Manager, set the variable `env.SERVICES.CONTENTSECURITYPOLICY`, in the `apigateway/groups/{group-id}/{instance-id}/conf/envSettings.props` file.

**Comment by andreamussap** [comment]
> We should add the removed info on the CSP header from #1835 here, namely this -
> 
> ===
> 
> You can configure the CSP header for both API Gateway and API Manager. To set the header, you must update the product's Java properties file, `envSettings.props`, which is available in the following locations:
> 
> * For API Gateway, set the variable `env.MANAGEMENT.CONTENTSECURITYPOLICY`, in the `apigateway/conf/envSettings.props` file.
> * For API Manager, set the variable `env.SERVICES.CONTENTSECURITYPOLICY`, in the `apigateway/groups/{group-id}/{instance-id}/conf/envSettings.props` file.

@sgoka-axway can you please address this in the new PR that you've opened to replace this one? Thanks

**Comment by sgoka-axway** [comment]
Thanks @mvenzke-axway for the comment, @andreamussap I will put it back in next commit.

**Pull request closed without merging**
