### PR TITLE
Create page in AMPLIFY Unified Catalog “discover-and-consume-catalog-assets-3”

### PR DESCRIPTION
**Pull request by jnamburi**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by andreamussap** [comment]
Hi @jnamburi this PR cannot be merged until you sign the Axway CLA - please see https://axway-open-docs.netlify.app/docs/contribution_guidelines/#before-you-start

**Comment by jnamburi** [comment]
@andreamussap Apologies, I signed the Axway CLA this morning!

**Comment by alexearnshaw** [comment]
@jnamburi I've reviewed this and updated it for Axway style etc. I've also deleted the integration builder page that contained some of this content. Thanks!

**Comment by alexearnshaw** [comment]
### Thank you
We really appreciate your contribution and thank you for helping us to improve this documentation!
 
### Where to find the updated documentation
An Axway technical writer has reviewed and merged your PR, which is now available on the following sites:
Netlify (staging): https://axway-open-docs.netlify.com/docs/
Zoomin (production): https://docs.axway.com/bundle/axway-open-docs/
 
### Send us your feedback
If you have a moment, please complete the following 2 minute survey to give us your feedback on this process and help us make it even better:
https://www.surveymonkey.com/r/PJ5HQFD

**Pull request merged**
