### PR TITLE
APIGOV-17765 Update CLI docs with info regarding new Axway Central CLI Package; change 'AMPLIFY' to 'Amplify'

### PR DESCRIPTION
**Pull request by rsavajiyani**
Thank you for your contribution to the Axway-Open-Docs repo.

## Describe the changes

- Updated information regarding the new 'Axway Central CLI' extension, including new installation instructions.
- Changing 'AMPLIFY' to 'Amplify' on pages I touched during the 'Axway Central CLI' updates; the rest will be handled in future doc updates
- Change 'Amplify CLI' core package references to 'Axway CLI' core package references

## Deploy preview link

https://deploy-preview-1751--axway-open-docs.netlify.app/docs/central/cli_central/cli_install/

^^ That cli_install file contains the bulk of the changes. The remainder of the changes are minor(see above) and spread throughout the rest of the docs portal.

_Although Netlify will add this link below, it will redirect to the main page of the documentation, not to an specific page._

## Checklist for contributors

Before submitting this PR, please make sure:

* [X] You have read the [contribution guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/)
* [X] You have signed the [Axway CLA](https://cla.axway.com/)
* [X] You have verified the technical accuracy of your change
* [X] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)
* [X] You have followed the [Markdown guidelines](https://axway-open-docs.netlify.com/docs/contribution_guidelines/writing_markdown/)  (unless this is is a Netlify CMS contribution)
* [x] You have verified that all status checks have passed

_Put an x in the boxes that apply. This is simply a reminder of what we are going to look for before merging your change._

### CODE REVIEW

**Comment by cbordier** [comment]
@rsavajiyani, I am waiting for Lisa to check if it has no impact when you change the linkTitle. Then I will be able to approve.

**Comment by andreamussap** [comment]
> @rsavajiyani, I am waiting for Lisa to check if it has no impact when you change the linkTitle. Then I will be able to approve.

@cbordier The `linkTitle` property is the lable for the left-side menu and for the breadcrumb.

PR-1751_linktitle

**Review by cbordier — APPROVED** [review]
I approve the changes

**Comment by lbadenhop** [comment]
@robertengaxway, @georgiana-caras  - please review today so I review and merge.

**Review by georgiana-caras — APPROVED** [review]

**Review by robertengaxway — APPROVED** [review]
I approved

**Review by lbadenhop — APPROVED** [review]

**Pull request merged**
