### PR TITLE
Update page in Connect API Manager “tips-troubleshooting-and-limitations”

### PR DESCRIPTION
**Pull request by cbordier**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by cbordier** [comment]
Hi @lbadenhop 
A new tips coming from experience day today with the mission 2020 SWAT team.
Can you review it and proceed?
Cyrille

**Comment by lbadenhop** [comment]
Hi @alexearnshaw -- please bypass the CLA check and merge / upload to docs.axway.com asap. There is an urgent request for the docs to be published on the portal.  Thanks.

**Comment by alexearnshaw** [comment]
@lbadenhop so sorry I missed this comment! I've merged this now and the CLA check should be fixed for all PRs going forward.
Will upload to docs.axway.com now too.

**Comment by lbadenhop** [comment]
@alexearnshaw  Thanks!

**Comment by alexearnshaw** [comment]
@lbadenhop @cbordier I had some issues with the CI but it's all resolved now I think and this is now on docs.axway.com

**Pull request merged**
